function Figure_model_parameters(plt, xfit, session)
%FIGURE_MODEL_PARAMETERS Plot parameters of each animal's best model.

    model_names = ["Model 1", "Model 1v", "Model 2", ...
        "Model 2v", "Model 3", "Model 3v"];
    model_parameter_names = { ...
        {'beta', 'k', 'thres'}, ...
        {'beta', 'k', 'thres'}, ...
        {'beta', 'k', 'thres', 'biasYP'}, ...
        {'beta', 'k', 'thres', 'biasYP'}, ...
        {'beta', 'k', 'thres', 'timeYP'}, ...
        {'beta', 'k', 'thres', 'timeYP'}};
    animals = ["S", "T"];
    n_models = numel(model_names);
    n_animals = numel(animals);

    assert(iscell(xfit) && size(xfit, 1) == n_models, ...
        'xfit must contain six model rows.');
    assert(istable(session) && ismember('animal', ...
        session.Properties.VariableNames), ...
        'session must be a table containing variable animal.');
    assert(size(xfit, 2) == height(session), ...
        'The number of fitted sessions must match the session table.');
    assert(all(cellfun(@(fit)isstruct(fit) && isfield(fit, 'AIC'), ...
        xfit), 'all'), ...
        'Every session fit must contain AIC.');

    AIC = cellfun(@(fit)fit.AIC, xfit);
    assert(all(isfinite(AIC), 'all'), ...
        'All session-level AIC values must be finite.');

    session_ids = cell(1, n_animals);
    best_models = nan(1, n_animals);
    parameter_values = cell(4, n_animals);
    p_best_all = nan(n_animals, n_models);
    for animali = 1:n_animals
        session_ids{animali} = session.animal == animals(animali);
        assert(any(session_ids{animali}), ...
            'No sessions were found for animal %s.', animals(animali));
        [~, session_best_models] = min( ...
            AIC(:, session_ids{animali}), [], 1);
        p_best_all(animali, :) = arrayfun( ...
            @(modeli)mean(session_best_models == modeli), 1:n_models);
        [~, best_models(animali)] = max(p_best_all(animali, :));

        parameter_names = ...
            model_parameter_names{best_models(animali)};
        assert(numel(parameter_names) == 4, ...
            ['The dominant model for Monkey %s is %s, which does not ' ...
            'have four fitted parameters.'], animals(animali), ...
            model_names(best_models(animali)));
        animal_fits = xfit(best_models(animali), ...
            session_ids{animali});
        for parameteri = 1:4
            parameter_name = parameter_names{parameteri};
            assert(all(cellfun(@(fit)isfield(fit, parameter_name), ...
                animal_fits)), ...
                'Parameter %s is missing from a best-model fit.', ...
                parameter_name);
            parameter_values{parameteri, animali} = cellfun( ...
                @(fit)fit.(parameter_name), animal_fits);
        end
        assert(all(parameter_values{1, animali} > 0), ...
            'The fitted beta values must be positive to plot sigma.');
        parameter_values{1, animali} = ...
            1./parameter_values{1, animali};
    end

    plt.figure(1, 2, 'is_title', 'all', 'pixel_w', 600);
    parameter_labels = { ...
        {'\sigma', 'k', '\theta', '\Delta t'}, ...
        {'\sigma', 'k', '\theta', '\beta'}};
    parameter_ticks = { ...
        {0.1:0.1:0.5, 0:0.2:1.2, 0:1:6, 0:0.2:1}, ...
        {0.1:0.1:0.5, 0:0.2:1.2, 0:0.2:1, 0:0.1:0.5}};
    for animali = 1:n_animals
        plt.ax(1, animali);
        values = parameter_values(:, animali);
        if animali == 2
            values{4} = -values{4};
        end
        labels = parameter_labels{animali};
        ticks = parameter_ticks{animali};
        panel_title = sprintf('%s: %s parameters', ...
            plt.custom_vars.name_monkeys(animali), ...
            model_names(best_models(animali)));
        plt.matlabax(@(~)plot_parameter_panel( ...
            values, labels, ticks, panel_title));
    end

    plt.addABCs('AB');
    plt.update('model parameters');
end

function plot_parameter_panel(values, labels, ticks, panel_title)
%PLOT_PARAMETER_PANEL Draw four independently scaled parameter box plots.
    ax = gca;
    font_size = ax.FontSize;
    line_width = ax.LineWidth;
    hold(ax, 'on');
    ax.Visible = 'off';
    ax.XLim = [0.45 4.45];
    ax.YLim = [0 1];

    y_positions = [0.12 0.50 0.88];
    for parameteri = 1:4
        parameter = values{parameteri}(:);
        assert(all(isfinite(parameter)), ...
            'All plotted parameter values must be finite.');
        tick_values = ticks{parameteri};
        parameter_limits = tick_values([1 end]);
        normalized = y_positions(1) + ...
            (parameter - parameter_limits(1))/diff(parameter_limits) * ...
            diff(y_positions([1 3]));

        boxchart(ax, parameteri*ones(size(normalized)), normalized, ...
            'BoxFaceColor', [0.35 0.35 0.35], ...
            'MarkerColor', [0.20 0.20 0.20], ...
            'BoxWidth', 0.38);

        axis_x = parameteri - 0.30;
        line(ax, [axis_x axis_x], y_positions([1 3]), ...
            'Color', 'black', 'LineWidth', line_width);
        tick_positions = linspace(y_positions(1), ...
            y_positions(3), numel(tick_values));
        for ticki = 1:numel(tick_values)
            line(ax, axis_x + [-0.025 0], ...
                tick_positions(ticki)*[1 1], ...
                'Color', 'black', 'LineWidth', line_width);
            tick_value = tick_values(ticki);
            if abs(tick_value) < ...
                    1e-6*max(1, max(abs(tick_values)))
                tick_label = '0';
            else
                tick_label = sprintf('%.2g', tick_value);
            end
            text(ax, axis_x - 0.04, tick_positions(ticki), ...
                tick_label, ...
                'HorizontalAlignment', 'right', ...
                'VerticalAlignment', 'middle', ...
                'FontSize', font_size);
        end
        text(ax, parameteri, 0.015, labels{parameteri}, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', ...
            'Interpreter', 'tex', 'FontSize', font_size + 5);
    end

    text(ax, 2.45, 1.1, panel_title, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontSize', font_size + 5);
end
