function Figure_model_posteriorchecks(plt, games_all, model_fits)
%FIGURE_MODEL_POSTERIORCHECKS Plot observed choices against model-specific DV.

    drop = double(plt.custom_vars.drop(:)');
    delay = double(plt.custom_vars.delay(:)');
    model_names = ["Model 1", "Model 1v", "Model 2", ...
        "Model 2v", "Model 3", "Model 3v"];
    model_classes = {'Model1', 'Model1t', 'Model2', ...
        'Model2t', 'Model3', 'Model3t'};
    delay_levels = [1 5 10];
    yellow_colors = [0.98 0.82 0.25; 0.90 0.62 0.00; 0.60 0.36 0.00];
    purple_colors = [0.72 0.52 0.85; 0.52 0.24 0.68; 0.40 0.18 0.60];
    yellow_model_color = yellow_colors(2, :);
    purple_model_color = purple_colors(2, :);
    model1_color = [0.45 0.45 0.45];
    is_yellow_first = [true, false];
    n_animals = 2;
    n_models = numel(model_names);
    n_conditions = numel(drop);

    assert(numel(delay) == n_conditions, ...
        'Drop and delay must define the same number of conditions.');
    assert(numel(games_all) == n_animals && ...
        all(cellfun(@istable, games_all)), ...
        'games_all must contain one pooled trial table for each animal.');

    % Pool trials across sessions within each animal. These observed values
    % are shared by all six model panels for that animal.
    observed_accept = nan(n_animals, n_conditions, 2);
    for animali = 1:n_animals
        animal_trials = games_all{animali};
        yellow_first = animal_trials.cue1 == "yellow";
        for orderi = 1:2
            for condi = 1:n_conditions
                trial_id = animal_trials.condition == condi & ...
                    yellow_first == is_yellow_first(orderi) & ...
                    ~isnan(animal_trials.choice);
                if any(trial_id)
                    observed_accept(animali, condi, orderi) = ...
                        mean(animal_trials.choice(trial_id));
                end
            end
        end
    end

    assert(size(model_fits, 1) >= n_models && ...
        size(model_fits, 2) >= n_animals, ...
        'modelfit_overall must contain six models for two animals.');
    assert(all(cellfun(@(fit)isstruct(fit) && ...
        all(isfield(fit, {'k', 'LL'})), ...
        model_fits(1:n_models, 1:n_animals)), 'all'), ...
        'Every overall model fit must contain k and LL.');
    model_ll = cellfun(@(fit)fit.LL, ...
        model_fits(1:n_models, 1:n_animals));
    [~, best_model] = max(model_ll, [], 1);

    group_title_fontsize = plt.param_plt.fontsize_title;
    original_legend_fontsize = plt.param_plt.fontsize_leg;
    plt.param_plt.fontsize_leg = plt.param_plt.fontsize_leg + 3;
    plt.figure(3, 4, 'is_title', 'all', ...
        'gapH_custom', [2 0 0 0], ...
        'gapW_custom', [0 0 0 0 7]);

    for familyi = 1:3
        for varianti = 1:2
            modeli = 2*(familyi - 1) + varianti;
            for animali = 1:n_animals
                axi = 2*(animali - 1) + varianti;
                plt.ax(familyi, axi);

                model_fit = model_fits{modeli, animali};
                inferred_value = compute_DV(drop, delay, model_fit.k);
                model = feval(model_classes{modeli});
                params = cellfun(@(name)model_fit.(name), ...
                    model.name_parameters);
                value_span = max(inferred_value) - min(inferred_value);
                if value_span == 0
                    value_span = 1;
                end
                xlims = [min(inferred_value) - 0.08*value_span, ...
                    max(inferred_value) + 0.08*value_span];

                yellow_accept = observed_accept(animali, :, 1);
                purple_accept = observed_accept(animali, :, 2);
                if varianti == 1
                    curve_value = linspace( ...
                        min(inferred_value), max(inferred_value), 501);
                    curve_delay = zeros(size(curve_value));
                    curve_yellow = model.policy(params, ...
                        curve_value(:), curve_delay(:), ...
                        true(numel(curve_value), 1));
                    curve_purple = model.policy(params, ...
                        curve_value(:), curve_delay(:), ...
                        false(numel(curve_value), 1));
                    if modeli == 1
                        plt.plot(curve_value, curve_yellow', ...
                            [], 'line', 'color', model1_color, ...
                            'LineStyle', '-', 'LineWidth', 2);
                    else
                        plt.plot(curve_value, curve_yellow', ...
                            [], 'line', 'color', yellow_model_color, ...
                            'LineStyle', '-', 'LineWidth', 2);
                        plt.plot(curve_value, curve_purple', ...
                            [], 'line', 'color', purple_model_color, ...
                            'LineStyle', '-', 'LineWidth', 2);
                    end
                else
                    for delayi = 1:numel(delay_levels)
                        delay_id = delay == delay_levels(delayi);
                        curve_value = linspace( ...
                            min(inferred_value(delay_id)), ...
                            max(inferred_value(delay_id)), 501);
                        curve_delay = repmat( ...
                            delay_levels(delayi), size(curve_value));
                        curve_reward = curve_value .* ...
                            (1 + model_fit.k .* curve_delay);
                        curve_yellow = model.policy(params, ...
                            curve_reward(:), curve_delay(:), ...
                            true(numel(curve_value), 1));
                        curve_purple = model.policy(params, ...
                            curve_reward(:), curve_delay(:), ...
                            false(numel(curve_value), 1));
                        plt.plot(curve_value, curve_yellow', ...
                            [], 'line', ...
                            'color', yellow_colors(delayi, :), ...
                            'LineStyle', '-', 'LineWidth', 2, ...
                            'addtolegend', 0);
                        plt.plot(curve_value, curve_purple', ...
                            [], 'line', ...
                            'color', purple_colors(delayi, :), ...
                            'LineStyle', '-', 'LineWidth', 2, ...
                            'addtolegend', 0);
                    end
                end

                for delayi = 1:numel(delay_levels)
                    delay_id = delay == delay_levels(delayi);
                    plt.plot(inferred_value(delay_id), ...
                        yellow_accept(delay_id), [], 'line', ...
                        'color', yellow_colors(delayi, :), ...
                        'LineStyle', 'o', ...
                        'MarkerSize', 6, 'LineWidth', 1.2);
                end
                for delayi = 1:numel(delay_levels)
                    delay_id = delay == delay_levels(delayi);
                    plt.plot(inferred_value(delay_id), ...
                        purple_accept(delay_id), [], 'line', ...
                        'color', purple_colors(delayi, :), ...
                        'LineStyle', 's', ...
                        'MarkerSize', 6, 'LineWidth', 1.2, ...
                        'is_hollow_dot', true);
                end

                xlabel_text = '';
                if familyi == 3
                    xlabel_text = 'Model-inferred value';
                end
                ylabel_text = '';
                if ismember(axi, [1 3])
                    ylabel_text = 'p(accept)';
                end
                best_marker = '';
                if modeli == best_model(animali)
                    best_marker = '*';
                end
                model_title = sprintf('%s%s, LL = %.3f', ...
                    best_marker, char(model_names(modeli)), model_fit.LL);
                plt.setfig_ax('xlabel', xlabel_text, ...
                    'ylabel', ylabel_text, ...
                    'xlim', xlims, 'ylim', [0 1], ...
                    'ytick', 0:0.2:1, ...
                    'title', model_title);

                if familyi == 3 && varianti == 2 && animali == 2
                    plt.plot(xlims, [-1 -1], [], 'line', ...
                        'color', yellow_model_color, ...
                        'LineStyle', '-', 'LineWidth', 2);
                    plt.plot(xlims, [-1 -1], [], 'line', ...
                        'color', purple_model_color, ...
                        'LineStyle', '-', 'LineWidth', 2);
                    plt.plot(xlims, [-1 -1], [], 'line', ...
                        'color', model1_color, ...
                        'LineStyle', '-', 'LineWidth', 2);
                    plt.setfig_ax('legend', ...
                        {'Yellow first, 1 s', ...
                        'Yellow first, 5 s', ...
                        'Yellow first, 10 s', ...
                        'Purple first, 1 s', ...
                        'Purple first, 5 s', ...
                        'Purple first, 10 s', ...
                        'Model: yellow first', ...
                        'Model: purple first', ...
                        'Model: overall'}, ...
                        'legloc', 'EO');
                end
            end
        end
    end

    plt.matlab(@()add_group_title( ...
        'Monkey S', [1 2], group_title_fontsize));
    plt.matlab(@()add_group_title( ...
        'Monkey T', [3 4], group_title_fontsize));
    % plt.addABCs('ABGHCDIJEFKL')
    plt.addABCs('CDIJEFKLGHMN')
    plt.update('behavior_inferred_value');
    plt.param_plt.fontsize_leg = original_legend_fontsize;
end

function add_group_title(title_text, columns, font_size)
    axes_handles = findall(gcf, 'Type', 'axes');
    axes_positions = zeros(numel(axes_handles), 4);
    for axi = 1:numel(axes_handles)
        axes_positions(axi, :) = getpixelposition(axes_handles(axi));
    end
    column_lefts = unique(axes_positions(:, 1), 'sorted');
    is_target = ismember(axes_positions(:, 1), column_lefts(columns));
    group_left = min(axes_positions(is_target, 1));
    group_right = max(axes_positions(is_target, 1) + ...
        axes_positions(is_target, 3));
    figure_position = getpixelposition(gcf);
    group_center = (group_left + group_right) / (2*figure_position(3));
    title_width = 0.30;
    annotation(gcf, 'textbox', ...
        [group_center - title_width/2, 0.965, title_width, 0.025], ...
        'String', title_text, 'EdgeColor', 'none', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontSize', font_size, 'FontWeight', 'normal');
end
