function Figure_model_comparison(plt, xfit, session)
%FIGURE_MODEL_COMPARISON Compare session-level AIC across choice models.

    model_names = ["Model 1", "Model 1t", "Model 2", ...
        "Model 2t", "Model 3", "Model 3t"];
    animals = ["S", "T"];
    n_models = numel(model_names);
    n_animals = numel(animals);

    assert(iscell(xfit) && size(xfit, 1) == n_models, ...
        'xfit must contain six model rows.');
    assert(istable(session) && ismember('animal', ...
        session.Properties.VariableNames), ...
        'session must be a table containing variable animal.');
    assert(size(xfit, 2) == height(session), ...
        'The number of fitted sessions must match the session table.');
    assert(all(cellfun(@(fit)isstruct(fit) && isfield(fit, 'AIC'), ...
        xfit), 'all'), ...
        'Every session fit must contain AIC.');

    AIC = cellfun(@(fit)fit.AIC, xfit);
    assert(all(isfinite(AIC), 'all'), ...
        'All session-level AIC values must be finite.');

    plt.figure(2, 2, 'is_title', 'all');
    for animali = 1:n_animals
        session_id = session.animal == animals(animali);
        assert(any(session_id), ...
            'No sessions were found for animal %s.', animals(animali));
        animal_AIC = AIC(:, session_id)';
        plt.ax(1, animali);
        [mean_AIC, se_AIC] = W.avse(animal_AIC);
        plt.plot(1:n_models, mean_AIC, se_AIC, 'bar', ...
            'color', 'black');
        plt.setfig_ax('xtick', 1:n_models, ...
            'xticklabel', model_names, ...
            'ylabel', 'AIC', ...
            'title', plt.custom_vars.name_monkeys(animali));
        plt.ax(2, animali);
        [~, best_model] = min(animal_AIC, [], 2);
        p_best = arrayfun(@(modeli)mean(best_model == modeli), ...
            1:n_models);
        plt.plot(1:n_models, p_best, [], 'bar', ...
            'color', 'black');
        plt.setfig_ax('xtick', 1:n_models, ...
            'xticklabel', model_names, ...
            'ylabel', 'Proportion best fit', ...
            'ylim', [0 1], 'ytick', 0:0.2:1);
    end

    plt.addABCs('ABCD');
    plt.update('model comparison');
end
