function Figure_behavior_base(plt, games_all, xfit)
    % compute choice curve, and condition means
    c0 = W.cellfun_vertcat(@(g)W.cond_average_tab(g, 'condition', 'choice'), games_all);
    v1 = W.cellfun_vertcat(@(g)W.cond_average_tab(g, 'condition', 'DV_overall'), games_all);
    % Figure 2 - behavior
    params = {xfit{1,1}, xfit{1,2}};
    
    xlms = {[0 3], [0 4]};
    point_labels = 'adgbehcfi';
    label_dx = { ...
        [0.02 -0.04 0.02 0.02 -0.04 0.02 0.02 -0.02 0.02], ...
        [0.02 0.02 -0.04 0.02 -0.04 -0.04 0.02 0.02 0.02]};
    label_dy = { ...
        [-0.025 0.025 -0.025 -0.025 -0.025 0.020 -0.025 -0.035 -0.025], ...
        [0.015 -0.025 -0.025 -0.025 0.025 -0.025 -0.025 -0.025 -0.025]};
    plt.figure(1,2, 'is_title', 'all');
    for i = 1:2
        plt.ax(1, i);
        xs = 0:0.01:5;
        x = params{i};
        f = @(V)W.col_select(W_RL.softmax_binary(x.thres, V, x.beta),2);
        cp = arrayfun(@(x)f(x), xs);
        plt.plot(xs, cp, [], 'line', 'color', 'black', 'LineWidth', 2);
        sp = 'ooosssddd';
        col = 'brgbrgbrg';
        for j = 1:9
            plt.scatter(v1.avDV_OVERALL(i,j), c0.avCHOICE(i, j), [], 'shape', sp(j), ...
                'dotsize', 7, 'color', col(j));
            plt.matlabax(@(~)text( ...
                v1.avDV_OVERALL(i,j) + label_dx{i}(j) .* diff(xlms{i}), ...
                c0.avCHOICE(i,j) + label_dy{i}(j), point_labels(j), ...
                'FontSize', 8, 'Color', [0.25 0.25 0.25], ...
                'HorizontalAlignment', 'left', 'VerticalAlignment', 'middle'));
        end
        plt.matlabax(@(~)set(findobj(gca, 'Type', 'line', ...
            '-not', 'Marker', 'none'), 'LineWidth', 2));
        if i == 2
            plt.matlabax(@(ax)legend(ax, [ ...
                line(ax, nan, nan, 'LineStyle', 'none', 'Marker', 'o', ...
                    'MarkerSize', 7, 'MarkerEdgeColor', 'black', 'LineWidth', 2); ...
                line(ax, nan, nan, 'LineStyle', 'none', 'Marker', 's', ...
                    'MarkerSize', 7, 'MarkerEdgeColor', 'black', 'LineWidth', 2); ...
                line(ax, nan, nan, 'LineStyle', 'none', 'Marker', 'd', ...
                    'MarkerSize', 7, 'MarkerEdgeColor', 'black', 'LineWidth', 2); ...
                line(ax, nan, nan, 'Color', 'b', 'LineWidth', 2); ...
                line(ax, nan, nan, 'Color', 'r', 'LineWidth', 2); ...
                line(ax, nan, nan, 'Color', 'g', 'LineWidth', 2)], ...
                {'Reward 2 drops', 'Reward 4 drops', 'Reward 6 drops', ...
                'Delay Short (1s)', 'Delay Medium (5s)', 'Delay Long (10s)'}, ...
                'Location', 'southeast', 'Box', 'off'));
        end
        plt.setfig_ax('ylabel', 'Acceptance Rate (%)', 'xlabel', 'Discounted Value', 'ylim', [0 1], ...
            'ytick', [0:.1:1], 'title', plt.custom_vars.name_monkeys(i), 'xlim', xlms{i}, ...
            'yticklabel', [0:10:100]);   
    end
    plt.addABCs('AB');
    plt.update('behavior');
end
