valueAxis = W.load('../../TempData/value_axisGO_control_for_choicemotor.mat');
rng(1, 'twister');
baselineWindow = [-250 0];
axisNames = ["Value", "Motor", "Choice"];
projections = cell(numel(axisNames), 2);
basePs = cell(numel(axisNames), 2);
regressionDiagnostics = cell(1,2);
adjustment = W.struct( ...
    'model', ['condition-by-color marginal means + additive choice ' ...
    '+ additive release1'], ...
    'reference', ...
    'choice and release1 held at their session-wide means', ...
    'interpretation', ...
    ['Yellow/Purple effect adjusted for additive choice and release1; ' ...
    'higher-order color/choice/release interactions are not identifiable']);
for animalIndex = 1:2
    goData = go{animalIndex};
    gameIDs = unique(goData.info_cells.gameID);
    animalGames = vertcat(goData.games{gameIDs});
    valueResult = valueAxis.animals(animalIndex);
    axesUnit = { ...
        valueResult.axis_value_unit, ...
        valueResult.axis_motor_unit, ...
        valueResult.axis_choice_unit};
    %
    nNeurons = numel(goData.cells);
    nConditions = 9;
    nColors = 2;
    nTimes = numel(goData.time_at);
    trajectories = nan(nNeurons, nConditions, nColors, nTimes);
    basetrajectories = nan(nNeurons, nConditions, nColors, 5);
    regressionDiagnostics{animalIndex} = table( ...
        'Size', [nNeurons 4], ...
        'VariableTypes', {'double', 'double', 'double', 'double'}, ...
        'VariableNames', {'n_trials', 'n_predictors', ...
        'design_rank', 'condition_number'});
    baselineMask = goData.time_at >= baselineWindow(1) & ...
        goData.time_at < baselineWindow(2);
    for neuronIndex = 1:nNeurons
        spikes = goData.cells{neuronIndex};
        game = goData.games{goData.info_cells.gameID(neuronIndex)};
        
        [adjustedMeans, diagnostic] = adjustedColorMeans( ...
            spikes, game, nConditions, nColors);
        regressionDiagnostics{animalIndex}.n_trials(neuronIndex) = ...
            diagnostic.n_trials;
        regressionDiagnostics{animalIndex}.n_predictors(neuronIndex) = ...
            diagnostic.n_predictors;
        regressionDiagnostics{animalIndex}.design_rank(neuronIndex) = ...
            diagnostic.design_rank;
        regressionDiagnostics{animalIndex}.condition_number(neuronIndex) = ...
            diagnostic.condition_number;

        for condition = 1:nConditions
            for colorIndex = 1:nColors
                trajectory0 = reshape(adjustedMeans( ...
                    condition, colorIndex, :), 1, []);
                baseT = mean(trajectory0(baselineMask), 'omitnan');
                trajectories(neuronIndex, condition, ...
                    colorIndex, :) = trajectory0 - baseT;
                basetrajectories(neuronIndex, condition, ...
                    colorIndex, 1) = baseT;
                for wi = 2:5
                    tbaselineMask = ...
                        goData.time_at >= baselineWindow(1) + ...
                        250*(wi - 1) & ...
                        goData.time_at < baselineWindow(2) + ...
                        250*(wi - 1);
                    basetrajectories(neuronIndex, condition, ...
                        colorIndex, wi) = mean( ...
                        trajectory0(tbaselineMask), 'omitnan');
                end
            end
        end
    end
    for axisIndex = 1:numel(axisNames)
        unitAxes = axesUnit{axisIndex};
        projections{axisIndex, animalIndex} = reshape( ...
            unitAxes'*reshape(trajectories, nNeurons, []), ...
            [], nConditions, nColors, nTimes);
        basePs{axisIndex, animalIndex} = reshape( ...
            unitAxes'*reshape(basetrajectories, nNeurons, []), ...
            [], nConditions, nColors, 5);
    end
end
W.save("../../TempData/projections_YP_codex.m", ...
    'projections', projections, ...
    'basePs', basePs, ...
    'axisNames', axisNames, ...
    'trainingWindows', valueAxis.settings.training_window_ms, ...
    'regressionDiagnostics', regressionDiagnostics, ...
    'adjustment', adjustment);


function [adjustedMeans, diagnostic] = adjustedColorMeans( ...
        spikes, game, nConditions, nColors)
%ADJUSTEDCOLORMEANS Estimate cell means controlling choice and release1.
    nTrials = height(game);
    colorIndex = nan(nTrials, 1);
    colorIndex(game.cue1 == "yellow") = 1;
    colorIndex(game.cue1 == "purple") = 2;
    isValid = isfinite(game.condition) & ...
        isfinite(game.choice) & ...
        isfinite(game.release1) & ...
        isfinite(colorIndex) & ...
        all(isfinite(spikes), 2);
    assert(any(isValid), ...
        'No valid trials remain for adjusted Yellow/Purple means.');

    condition = game.condition(isValid);
    color = colorIndex(isValid);
    choice = double(game.choice(isValid));
    release = double(game.release1(isValid));
    cellIndex = (condition - 1)*nColors + color;
    nCells = nConditions*nColors;
    cellDesign = full(sparse( ...
        (1:sum(isValid))', cellIndex, 1, sum(isValid), nCells));
    assert(all(sum(cellDesign, 1) > 0), ...
        'Every condition/color cell must contain valid trials.');

    choice = choice - mean(choice);
    release = release - mean(release);
    design = [cellDesign, choice, release];
    designRank = rank(design);
    assert(designRank == size(design, 2), ...
        ['The additive color/choice/release1 model is rank deficient. ' ...
        'The adjusted color effect is not identifiable.']);

    coefficients = design \ spikes(isValid, :);
    adjustedMeans = reshape(coefficients(1:nCells, :), ...
        nColors, nConditions, []);
    adjustedMeans = permute(adjustedMeans, [2 1 3]);
    diagnostic = struct( ...
        'n_trials', sum(isValid), ...
        'n_predictors', size(design, 2), ...
        'design_rank', designRank, ...
        'condition_number', cond(design));
end