data = W.load('../../TempData/data');
go = data.go;
go{3} = W.format_combinecells(go);
timeat = go{1}.time_at;
ntime = length(timeat);
plt = SW_plt_from_yml('../fig.yml');
%% go period
% %% ANOVA: drop + delay + interaction + yellow/purple + motor + choice
% factornames = {'drop', 'delay', 'choice', 'motor', 'GO cue'};
% factornames_in_data = {'drop', 'delay', 'choice', 'release1', 'cue1'};
% model = [1,0,0,0,0; ...
%          0,1,0,0,0; ...
%          1,1,0,0,0; ...
%          0,0,1,0,0; ...
%          0,0,0,1,0; ...
%          0,0,0,0,1];
% anv = {};
% for i = 1:2
%     d = go{i};
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
%     % merge factors
%     anv{i} = W.anovan_mergefactors(anv{i}, {'delay', 'drop', 'drop*delay'}, {'drop|delay'});
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_all_factors', 'anv', anv);
% %% Figure - ANOVA
% anv = W.load('../../TempData/result/anvGO_all_factors');
% SW_fig(plt, anv{1}, anv{2}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
%     'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
%      'data_axes', 1, 2, 1, 2, ...
%      'varargin_axes', {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      'ABC_axes', 'ABCD', 'nx', 2, 'ny', 2, ...
%      'varargin_fig', 'is_title', 'all', 'savename', 'anvGO_all_factors');
% 
% 
% %% improve yellow/purple by selecting only behavioral conditions where it matters
% factornames = {'drop', 'delay', 'choice', 'motor', 'GO cue'};
% factornames_in_data = {'drop', 'delay', 'choice', 'release1', 'cue1'};
% model = [1,0,0,0,0; ...
%          0,1,0,0,0; ...
%          1,1,0,0,0; ...
%          0,0,1,0,0; ...
%          0,0,0,1,0; ...
%          0,0,0,0,1];
% anv = {};
% ps = W.load('../../TempData/behavior_pYP');
% for i = 1:2
%     d = go{i};
%     idYP = find(ps(i,:) * 9 < 0.05);
%     for gi = 1:length(d.games)
%         g = d.games{gi};
%         g.cue1(~ismember(g.condition, idYP)) = "other";
%         d.games{gi} = g;
%     end
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
%     % merge factors
%     anv{i} = W.anovan_mergefactors(anv{i}, {'delay', 'drop', 'drop*delay'}, {'drop|delay'});
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_YP_other', 'anv', anv);
% %% v2
% factornames = {'drop', 'delay', 'choice', 'motor', 'GO cue'};
% factornames_in_data = {'drop', 'delay', 'choice', 'release1', 'cue1'};
% model = [1,0,0,0,0; ...
%          0,1,0,0,0; ...
%          1,1,0,0,0; ...
%          0,0,1,0,0; ...
%          0,0,0,1,0; ...
%          0,0,0,0,1];
% anv = {};
% ps = W.load('../../TempData/behavior_pYP');
% for i = 1:2
%     d = go{i};
%     idYP = find(ps(i,:) * 9 < 0.05);
%     for gi = 1:length(d.games)
%         g = d.games{gi};
%         g.cue1(ismember(g.condition, idYP)) = "other";
%         d.games{gi} = g;
%     end
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
%     % merge factors
%     anv{i} = W.anovan_mergefactors(anv{i}, {'delay', 'drop', 'drop*delay'}, {'drop|delay'});
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_YP_opposite', 'anv', anv);
% %% control
% factornames = {'drop', 'delay', 'choice', 'motor', 'GO cue'};
% factornames_in_data = {'drop', 'delay', 'choice', 'release1', 'cue1'};
% model = [1,0,0,0,0; ...
%          0,1,0,0,0; ...
%          1,1,0,0,0; ...
%          0,0,1,0,0; ...
%          0,0,0,1,0; ...
%          0,0,0,0,1];
% anv = {};
% ps = W.load('../../TempData/behavior_pYP');
% for i = 1:2
%     d = go{i};
%     idYP = find(ps(i,:) * 9 < 0.05);
%     for gi = 1:length(d.games)
%         g = d.games{gi};
%         g.cue1(ismember(g.condition, idYP)) = "main";
%         g.cue1(~ismember(g.condition, idYP)) = "other";
%         d.games{gi} = g;
%     end
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
%     % merge factors
%     anv{i} = W.anovan_mergefactors(anv{i}, {'delay', 'drop', 'drop*delay'}, {'drop|delay'});
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_YP_control', 'anv', anv);
% %%
% anv = W.load('../../TempData/result/anvGO_YP_other')
% anv = W.load('../../TempData/result/anvGO_YP_opposite')
% SW_fig(plt, anv{1}, anv{2}, anv{3}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
%     'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
%      'data_axes', 1, 2, 3, 1, 2, 3, ...
%      'varargin_axes', {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', ''}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 3, ...
%      'varargin_fig', 'is_title', 'all');
%% ANOVA: condition 
factornames = {'condition', 'motor', 'GO cue', 'choice'};
factornames_in_data = {'condition', 'release1', 'cue1', 'choice'};
% nested = zeros(4,4);
% nested(3,1) = 1;
model = [1 0 0 0; 0 1 0 0; 0 0 0 1; 0 0 1 0];
anv = {};
for i = 1:2
    d = go{i};
    anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
        'factornames_in_data', factornames_in_data, ...
        'model', model);
end
% anv{3} = W.format_combinecells(anv);
W.save('../../TempData/result/anvGO_condition', 'anv', anv);
%% ANOVA: delay drop
factornames = {'delay', 'drop', 'motor', 'GO cue', 'choice'};
factornames_in_data = {'delay', 'drop', 'release1', 'cue1', 'choice'};
% nested = zeros(4,4);
% nested(3,1) = 1;
model = [1 0 0 0 0; 0 1 0 0 0; 1 1 0 0 0; 0 0 1 0 0; 0 0 0 0 1; 0 0 0 1 0];
anv = {};
for i = 1:2
    d = go{i};
    anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
        'factornames_in_data', factornames_in_data, ...
        'model', model);
end
% anv{3} = W.format_combinecells(anv);
W.save('../../TempData/result/anvGO_drop_delay', 'anv', anv);
%% ANOVA: predict accept
factornames = {'choice tendency', 'motor_tendency', 'motor', 'choice', 'DV', 'GO cue'};
factornames_in_data = {'pred_accept', 'pred_release', 'release1', 'choice', 'DV', 'cue1'};
anv = {};
for i = 1:2
    d = go{i};
    anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
        'factornames_in_data', factornames_in_data, ...
        'continuous', [1 2 5]);
end
% anv{3} = W.format_combinecells(anv);
W.save('../../TempData/result/anvGO_tendency', 'anv', anv);
%% ANOVA: predict accept
factornames = {'DV', 'choice tendency', 'motor_tendency', 'GO cue'};
factornames_in_data = {'DV', 'pred_accept', 'pred_release', 'cue1'};
anv = {};
for i = 1:2
    d = go{i};
    anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
        'factornames_in_data', factornames_in_data, ...
        'continuous', [1 2 3]);
end
% anv{3} = W.format_combinecells(anv);
W.save('../../TempData/result/anvGO_tendency2', 'anv', anv);
%% ANOVA: predict accept
factornames = {'DV', 'choice', 'motor', 'GO cue'};
factornames_in_data = {'DV', 'choice', 'release1', 'cue1'};
anv = {};
for i = 1:2
    d = go{i};
    anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
        'factornames_in_data', factornames_in_data, ...
        'continuous', [1 2 3]);
end
% anv{3} = W.format_combinecells(anv);
W.save('../../TempData/result/anvGO_tendency3', 'anv', anv);
%%
anv = W.load('../../TempData/result/anvGO_tendency');
SW_fig(plt, anv{1}, anv{2}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
    'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 2, 1, 2, ...
     'varargin_axes', {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 2, ...
     'varargin_fig', 'is_title', 'all', 'savename', 'anvGO_tendency');
%%
anv = W.load('../../TempData/result/anvGO_tendency2');
SW_fig(plt, anv{1}, anv{2}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
    'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 2, 1, 2, ...
     'varargin_axes', {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 2, ...
     'varargin_fig', 'is_title', 'all', 'savename', 'anvGO_tendency2');
%%
anv = W.load('../../TempData/result/anvGO_tendency3');
SW_fig(plt, anv{1}, anv{2}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
    'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 2, 1, 2, ...
     'varargin_axes', {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 2, ...
     'varargin_fig', 'is_title', 'all', 'savename', 'anvGO_tendency3');
%%
anv = W.load('../../TempData/result/anvGO_condition');
SW_fig(plt, anv{1}, anv{2}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
    'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 2, 1, 2, ...
     'varargin_axes', {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 2, ...
     'varargin_fig', 'is_title', 'all', 'savename', 'anova_GO');
%% drop delay
anv = W.load('../../TempData/result/anvGO_drop_delay');
for i = 1:2
    anv{i} = W.anovan_mergefactors(anv{i}, {'delay', 'drop', 'delay:drop'}, {'drop|delay'});
end
SW_fig(plt, anv{1}, anv{2}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
    'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 2, 1, 2, ...
     'varargin_axes', {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 2, ...
     'varargin_fig', 'is_title', 'all', 'savename', 'anova_drop_delay');

%%
is_sig_baseline = W.cellfun_horzcat(@(x)mean(x.is_significant(:,timeat < 0),2), anv{3}.cells);
is_sig = W.cellfun_horzcat(@(x)mean(x.is_significant(:,timeat >= 0),2), anv{3}.cells);
%%
anv = W.load('../../TempData/result/anvGO_condition');
SW_fig(plt, anv{1}, anv{2}, anv{3}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
    'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 2, 3, 1, 2, 3, ...
     'varargin_axes', {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', ''}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 3, ...
     'varargin_fig', 'is_title', 'all', 'savename', 'anova_GO');
% %% improve yellow/purple by selecting only behavioral conditions where it matters
% factornames = {'condition', 'motor', 'GO cue'};
% factornames_in_data = {'condition', 'release1', 'cue1'};
% model = [1,0,0; ...
%          0,1,0; ...
%          0,0,1];
% anv = {};
% ps = W.load('../../TempData/behavior_pYP');
% for i = 1:2
%     d = go{i};
%     idYP = find(ps(i,:) * 9 < 0.05);
%     for gi = 1:length(d.games)
%         g = d.games{gi};
%         g.cue1(~ismember(g.condition, idYP)) = "other";
%         d.games{gi} = g;
%     end
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_YP_other', 'anv', anv);
% %% v2
% factornames = {'condition', 'motor', 'GO cue'};
% factornames_in_data = {'condition', 'release1', 'cue1'};
% model = [1,0,0; ...
%          0,1,0; ...
%          0,0,1];
% anv = {};
% ps = W.load('../../TempData/behavior_pYP');
% for i = 1:2
%     d = go{i};
%     idYP = find(ps(i,:) * 9 < 0.05);
%     for gi = 1:length(d.games)
%         g = d.games{gi};
%         g.cue1(ismember(g.condition, idYP)) = "other";
%         d.games{gi} = g;
%     end
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_YP_opposite', 'anv', anv);
% %%
% anv = W.load('../../TempData/result/anvGO_YP');
% SW_fig(plt, anv{1}, anv{2}, anv{3}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
%     'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
%      'data_axes', 1, 2, 3, 1, 2, 3, ...
%      'varargin_axes', {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', ''}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 3, ...
%      'varargin_fig', 'is_title', 'all');
%%

kfold = 2;
results = cell(1,2);
W.print_mute_off;
for ai = 1:2
    d = go{ai};
    d = W.combinedcells_removeNAtrials(d);
    nmin = W.cellfun(@(x)min(W.count_cond(x.condition,1:9)), d.games);
    idx = find(nmin >= 10);
    idcell = ismember(d.info_cells.gameID, idx);
    d.info_cells = d.info_cells(idcell,:);
    d.cells = d.cells(idcell);

    [tr0, te0] = W.combinedcells_kfoldtrials_bycond(d, kfold, 'condition');
    out = cell(1,kfold);
    W.print('loop %d', ai);
    W.print_mute_on;
    i = 1;
    tr = W.pseudo_sampletrials_bycond(tr0{i}, 'condition', 80);
    te = W.pseudo_sampletrials_bycond(te0{i}, 'condition', 80);

    m1 = W.neuro_decode_slidingwindow(tr, 'cells', tr.games.delay, 'SVM', 'train', 'SVMfunc', 'continuous');
    r1 = W.neuro_decode_slidingwindow(te, 'cells', te.games.delay, m1.models, 'test', 'SVMfunc', 'continuous');

    m2 = W.neuro_decode_slidingwindow(tr, 'cells', tr.games.drop, 'SVM', 'train', 'SVMfunc', 'continuous');
    r2 = W.neuro_decode_slidingwindow(te, 'cells', te.games.drop, m2.models, 'test', 'SVMfunc', 'continuous');

    m3 = W.neuro_decode_slidingwindow(tr, 'cells', tr.games.DV, 'SVM', 'train', 'SVMfunc', 'continuous');
    r3 = W.neuro_decode_slidingwindow(te, 'cells', te.games.DV, m3.models, 'test', 'SVMfunc', 'continuous');

    out = W.struct('r_delay', r1, 'r_drop', r2, 'r_DV', r3, ...
        'md_delay', m1, 'md_drop', m2, 'md_DV', m3, ...
        'game_train', tr, 'game_test', te);
    W.print_mute_off;
    results{ai} = out;
end
W.save('decodingG', 'result', results);
%% decoding
results = W.load('decodingG');
cols = ["AZred20","AZcactus20","AZblue20", "AZred50","AZcactus50","AZblue50", "AZred","AZcactus","AZblue"];

plt.figure(3,2, 'is_title', 'all')
for ai = 1:2
    r0 = results{ai};
    r = cell(1,3);
    r{1} = W.average_bycond(r0.r_delay.ypredict, r0.game_test.games.condition, 1:9);
    r{2} = W.average_bycond(r0.r_drop.ypredict, r0.game_test.games.condition, 1:9);
    r{3} = W.average_bycond(r0.r_DV.ypredict, r0.game_test.games.condition, 1:9);
    tlt = {'drop', 'delay', 'DV'};
    for i = 1:3
        plt.ax(i, ai);
        % [av, se] = W.avse(r{i});
        av = r{i};
        plt.plot(timeat, av, [], 'line', 'color', cols);
        % plt.dashX(chance(i));
        % plt.dashY(0, [0 1]);
        plt.setfig_ax('xlabel', 'time (ms)', 'ylabel', 'decoding accuracy', 'title', tlt{ai}, ...
            'xlim', [-500 1000], 'ylim', []);
        
    end
end
plt.update('decodeG');



%% decoding analysis
kfold = 5;
results = cell(1,3);
for ai = 1:2
    d = go{ai};
    d = W.combinedcells_removeNAtrials(d);
    nmin = W.cellfun(@(x)min(W.count_cond(x.condition,1:9)), d.games);
    idx = find(nmin >= 10);
    idcell = ismember(d.info_cells.gameID, idx);
    d.info_cells = d.info_cells(idcell,:);
    d.cells = d.cells(idcell);

    [tr0, te0] = W.combinedcells_kfoldtrials_bycond(d, kfold, 'condition');
    out = cell(1,kfold);
    W.print('loop %d', ai);
    W.print_mute_on;
    for i = 1:kfold
        tr = W.pseudo_sampletrials_bycond(tr0{i}, 'condition', 80);
        te = W.pseudo_sampletrials_bycond(te0{i}, 'condition', 80);

        m1 = W.neuro_decode_slidingwindow(tr, 'cells', tr.games.delay, 'SVM', 'train', 'SVMfunc', 'discrete');
        r1 = W.neuro_decode_slidingwindow(te, 'cells', te.games.delay, m1.models, 'test', 'SVMfunc', 'discrete');

        m2 = W.neuro_decode_slidingwindow(tr, 'cells', tr.games.drop, 'SVM', 'train', 'SVMfunc', 'discrete');
        r2 = W.neuro_decode_slidingwindow(te, 'cells', te.games.drop, m2.models, 'test', 'SVMfunc', 'discrete');

        m3 = W.neuro_decode_slidingwindow(tr, 'cells', tr.games.condition, 'SVM', 'train', 'SVMfunc', 'discrete');
        r3 = W.neuro_decode_slidingwindow(te, 'cells', te.games.condition, m3.models, 'test', 'SVMfunc', 'discrete');

        out{i} = W.struct('r_delay', r1, 'r_drop', r2, 'r_interaction', r3)
    end
    W.print_mute_off;
    results{ai} = out;
end
W.save('decoding_GOOO', 'result', results);
%%
plt.figure(3,2, 'is_title', 'all')
for ai = 1:2
    r0 = results{ai};
    r = cell(1,3);
    r{1} = W.cellfun_vertcat(@(x)x.r_delay.ac_decode, r0);
    r{2} = W.cellfun_vertcat(@(x)x.r_drop.ac_decode, r0);
    r{3} = W.cellfun_vertcat(@(x)x.r_interaction.ac_decode, r0);
    chance = [1/3, 1/3, 1/9];
%     tlt = {'drop', 'delay', 'Drop x Delay'};
    for i = 1:3
        plt.ax(i, ai);
        [av, se] = W.avse(r{i});
        plt.plot(timeat, av, se, 'shade', 'color', plt.custom_vars.color_anova{i});
        plt.dashX(chance(i));
        plt.dashY(0, [0 1]);
        plt.setfig_ax('xlabel', 'time (ms)', 'ylabel', 'decoding accuracy', 'title', tlt{ai}, ...
            'xlim', [-500 1000]);
        if i == 3
            [av1, se1] = W.avse(r{1}.*r{2});
            [p] = W.stat_ttest(r{1}.*r{2}, r{3});
            tid = find(timeat > -500 & timeat < 1000);
            plt.plot(timeat, av1, se1, 'shade', 'color', 'black');
            plt.sigstar(timeat(tid), "top", p(tid), 'dx', 25)
            plt.setfig_ax('legend', {'data','independence'}, 'ylim', [0 1]);
        else
            plt.setfig_ax('ylim', [0 1]);
        end
    end
end
plt.update('decode_GOOO');