%% Regression of condition-baseline-corrected activity on choice and motor
% Response for trial i belonging to condition k:
%   Delta firing_i(t) = firing_i(t) -
%       mean firing for condition k during -250:0 ms before GO.
%
% Regression at every neuron and time point:
%   Delta firing_i(t) = alpha(t) + beta_C(t) C_i +
%       beta_M(t) M_i + beta_CM(t) C_i*M_i + epsilon_i(t),
% where C and M are effect-coded as -1/+1.

if ~exist('go', 'var')
    data = W.load('../../TempData/data');
    go = data.go;
end

valueAxes = W.load('../../TempData/value_axisGO');
axisWindowIndex = 1;
baselineWindow = [-250 0];
analysisWindows = [0 250; 250 500; 500 750; 750 1000];
animalNames = ["Monkey S", "Monkey T"];
parameterNames = ["Intercept", "Choice", ...
    "Release1", "Choice x Release1"];
componentNames = ["Intercept only", "Choice only", ...
    "Release1 only", "Choice x Release1 only", ...
    "Regression residual"];
animalColors = [0.15 0.45 0.75; 0.75 0.25 0.20];

pilot3Regression = struct;
pilot3Regression.model = [ ...
    "Delta firing(t) ~ 1 + choice + release1 + " ...
    "choice*release1"];
pilot3Regression.response = [ ...
    "Firing rate minus the neuron's condition-specific mean " ...
    "firing rate during -250:0 ms before GO"];
pilot3Regression.parameter_names = parameterNames;
pilot3Regression.component_names = componentNames;
pilot3Regression.reduced_model = ...
    "Delta firing(t) ~ 1 + choice + release1";
pilot3Regression.choice_only_model = ...
    "Delta firing(t) ~ 1 + choice";
pilot3Regression.motor_only_model = ...
    "Delta firing(t) ~ 1 + release1";
pilot3Rows = cell(0, 8);

for animalIndex = 1:numel(animalNames)
    goData = go{animalIndex};
    timeAt = goData.time_at;
    nNeurons = numel(goData.cells);
    nTimes = numel(timeAt);
    nParameters = numel(parameterNames);
    baselineMask = timeAt >= baselineWindow(1) & ...
        timeAt < baselineWindow(2);
    betaTime = nan(nNeurons, nParameters, nTimes);
    uniqueExplainedSS = nan(nNeurons, 3, nTimes);
    fullModelExplainedSS = nan(nNeurons, nTimes);
    totalSS = nan(nNeurons, nTimes);
    reducedBetaTime = nan(nNeurons, 3, nTimes);
    choiceOnlyBetaTime = nan(nNeurons, 2, nTimes);
    motorOnlyBetaTime = nan(nNeurons, 2, nTimes);
    conditionBaselines = nan(nNeurons, 9);
    correctedYPTrajectories = nan(nNeurons, 9, 2, nTimes);
    componentYPTrajectories = nan( ...
        nNeurons, 5, 9, 2, nTimes);
    reducedResidualYPTrajectories = nan( ...
        nNeurons, 9, 2, nTimes);
    choiceOnlyResidualYPTrajectories = nan( ...
        nNeurons, 9, 2, nTimes);
    motorOnlyResidualYPTrajectories = nan( ...
        nNeurons, 9, 2, nTimes);

    for neuronIndex = 1:nNeurons
        spikes = goData.cells{neuronIndex};
        game = goData.games{ ...
            goData.info_cells.gameID(neuronIndex)};
        assert(size(spikes, 1) == height(game), ...
            'Spike trials and behavioral trials must match.');

        deltaSpikes = nan(size(spikes));
        for condition = 1:9
            conditionMask = game.condition == condition;
            baselineValues = spikes(conditionMask, baselineMask);
            conditionBaseline = mean( ...
                baselineValues, 'all', 'omitnan');
            conditionBaselines(neuronIndex, condition) = ...
                conditionBaseline;
            deltaSpikes(conditionMask, :) = ...
                spikes(conditionMask, :) - conditionBaseline;
        end

        choiceCode = 2 * game.choice - 1;
        motorCode = 2 * game.release1 - 1;
        design = [ones(height(game), 1), choiceCode, ...
            motorCode, choiceCode .* motorCode];
        reducedDesign = design(:, 1:3);
        choiceOnlyDesign = design(:, 1:2);
        motorOnlyDesign = design(:, [1 3]);
        validBehavior = all(isfinite(design), 2);

        for timeIndex = 1:nTimes
            validTrials = validBehavior & ...
                isfinite(deltaSpikes(:, timeIndex));
            currentDesign = design(validTrials, :);
            currentReducedDesign = reducedDesign(validTrials, :);
            currentChoiceOnlyDesign = ...
                choiceOnlyDesign(validTrials, :);
            currentMotorOnlyDesign = ...
                motorOnlyDesign(validTrials, :);
            if rank(currentDesign) == nParameters
                currentResponse = deltaSpikes( ...
                    validTrials, timeIndex);
                fullCoefficients = ...
                    currentDesign \ currentResponse;
                betaTime(neuronIndex, :, timeIndex) = ...
                    fullCoefficients;

                fullResidual = currentResponse - ...
                    currentDesign*fullCoefficients;
                fullSSE = sum(fullResidual.^2);
                currentTotalSS = sum((currentResponse - ...
                    mean(currentResponse)).^2);
                totalSS(neuronIndex, timeIndex) = currentTotalSS;
                fullModelExplainedSS(neuronIndex, timeIndex) = ...
                    max(currentTotalSS - fullSSE, 0);

                % Drop one term from the full model at a time. The
                % increase in SSE is that term's unique contribution
                % conditional on the other two behavioral predictors.
                retainedColumns = { ...
                    [1 3 4], ... % omit choice
                    [1 2 4], ... % omit release1
                    [1 2 3]};    % omit choice x release1
                for predictorIndex = 1:numel(retainedColumns)
                    reducedForTerm = currentDesign(:, ...
                        retainedColumns{predictorIndex});
                    if rank(reducedForTerm) == ...
                            size(reducedForTerm, 2)
                        reducedCoefficientsForTerm = ...
                            reducedForTerm \ currentResponse;
                        reducedResidualForTerm = currentResponse - ...
                            reducedForTerm*reducedCoefficientsForTerm;
                        reducedSSEForTerm = ...
                            sum(reducedResidualForTerm.^2);
                        uniqueExplainedSS(neuronIndex, ...
                            predictorIndex, timeIndex) = ...
                            max(reducedSSEForTerm - fullSSE, 0);
                    end
                end
            end
            if rank(currentReducedDesign) == 3
                reducedBetaTime(neuronIndex, :, timeIndex) = ...
                    currentReducedDesign \ deltaSpikes( ...
                    validTrials, timeIndex);
            end
            if rank(currentChoiceOnlyDesign) == 2
                choiceOnlyBetaTime(neuronIndex, :, timeIndex) = ...
                    currentChoiceOnlyDesign \ deltaSpikes( ...
                    validTrials, timeIndex);
            end
            if rank(currentMotorOnlyDesign) == 2
                motorOnlyBetaTime(neuronIndex, :, timeIndex) = ...
                    currentMotorOnlyDesign \ deltaSpikes( ...
                    validTrials, timeIndex);
            end
        end

        betaIntercept = reshape(betaTime(neuronIndex, 1, :), ...
            1, nTimes);
        betaChoice = reshape(betaTime(neuronIndex, 2, :), ...
            1, nTimes);
        betaMotor = reshape(betaTime(neuronIndex, 3, :), ...
            1, nTimes);
        betaInteraction = reshape(betaTime(neuronIndex, 4, :), ...
            1, nTimes);
        interceptComponent = ones(height(game), 1) * ...
            betaIntercept;
        choiceComponent = choiceCode * betaChoice;
        motorComponent = motorCode * betaMotor;
        interactionComponent = (choiceCode .* motorCode) * ...
            betaInteraction;
        residualComponent = deltaSpikes - interceptComponent - ...
            choiceComponent - motorComponent - interactionComponent;
        componentData = {interceptComponent, choiceComponent, ...
            motorComponent, interactionComponent, residualComponent};
        reducedCoefficients = reshape( ...
            reducedBetaTime(neuronIndex, :, :), 3, nTimes);
        reducedResidual = deltaSpikes - ...
            reducedDesign * reducedCoefficients;
        choiceOnlyCoefficients = reshape( ...
            choiceOnlyBetaTime(neuronIndex, :, :), 2, nTimes);
        choiceOnlyResidual = deltaSpikes - ...
            choiceOnlyDesign * choiceOnlyCoefficients;
        motorOnlyCoefficients = reshape( ...
            motorOnlyBetaTime(neuronIndex, :, :), 2, nTimes);
        motorOnlyResidual = deltaSpikes - ...
            motorOnlyDesign * motorOnlyCoefficients;
        correctedDeltaSpikes = deltaSpikes - ...
            choiceComponent - motorComponent;

        isColor = {game.cue1 == "yellow", ...
            game.cue1 == "purple"};
        for condition = 1:9
            for colorIndex = 1:2
                trialMask = game.condition == condition & ...
                    isColor{colorIndex};
                if sum(trialMask) < 10
                    continue;
                end
                trajectory = mean( ...
                    correctedDeltaSpikes(trialMask, :), ...
                    1, 'omitnan');
                trajectory = trajectory - mean( ...
                    trajectory(baselineMask), 'omitnan');
                correctedYPTrajectories(neuronIndex, ...
                    condition, colorIndex, :) = trajectory;
                reducedResidualTrajectory = mean( ...
                    reducedResidual(trialMask, :), ...
                    1, 'omitnan');
                reducedResidualTrajectory = ...
                    reducedResidualTrajectory - mean( ...
                    reducedResidualTrajectory(baselineMask), ...
                    'omitnan');
                reducedResidualYPTrajectories(neuronIndex, ...
                    condition, colorIndex, :) = ...
                    reducedResidualTrajectory;
                choiceOnlyResidualTrajectory = mean( ...
                    choiceOnlyResidual(trialMask, :), ...
                    1, 'omitnan');
                choiceOnlyResidualTrajectory = ...
                    choiceOnlyResidualTrajectory - mean( ...
                    choiceOnlyResidualTrajectory(baselineMask), ...
                    'omitnan');
                choiceOnlyResidualYPTrajectories(neuronIndex, ...
                    condition, colorIndex, :) = ...
                    choiceOnlyResidualTrajectory;
                motorOnlyResidualTrajectory = mean( ...
                    motorOnlyResidual(trialMask, :), ...
                    1, 'omitnan');
                motorOnlyResidualTrajectory = ...
                    motorOnlyResidualTrajectory - mean( ...
                    motorOnlyResidualTrajectory(baselineMask), ...
                    'omitnan');
                motorOnlyResidualYPTrajectories(neuronIndex, ...
                    condition, colorIndex, :) = ...
                    motorOnlyResidualTrajectory;
                for componentIndex = 1:numel(componentNames)
                    componentTrajectory = mean( ...
                        componentData{componentIndex}(trialMask, :), ...
                        1, 'omitnan');
                    componentTrajectory = componentTrajectory - mean( ...
                        componentTrajectory(baselineMask), 'omitnan');
                    componentYPTrajectories(neuronIndex, ...
                        componentIndex, condition, colorIndex, :) = ...
                        componentTrajectory;
                end
            end
        end
    end

    rawValueAxis = valueAxes.animals(animalIndex). ...
        axis_unit(:, axisWindowIndex);
    validNeurons = all(reshape( ...
        isfinite(betaTime), nNeurons, []), 2) & ...
        isfinite(rawValueAxis);
    betaTime(~validNeurons, :, :) = 0;
    valueAxis = rawValueAxis;
    valueAxis(~validNeurons) = 0;
    valueAxis = valueAxis / norm(valueAxis);

    parameterProjection = reshape(valueAxis' * ...
        reshape(betaTime, nNeurons, []), ...
        nParameters, nTimes);

    validCorrectedNeurons = all(reshape( ...
        isfinite(correctedYPTrajectories), ...
        nNeurons, []), 2) & isfinite(rawValueAxis);
    correctedYPTrajectories(~validCorrectedNeurons, :, :, :) = 0;
    correctedValueAxis = rawValueAxis;
    correctedValueAxis(~validCorrectedNeurons) = 0;
    correctedValueAxis = correctedValueAxis / ...
        norm(correctedValueAxis);
    correctedYPProjection = reshape(correctedValueAxis' * ...
        reshape(correctedYPTrajectories, nNeurons, []), ...
        9, 2, nTimes);

    validComponentNeurons = all(reshape( ...
        isfinite(componentYPTrajectories), ...
        nNeurons, []), 2) & isfinite(rawValueAxis);
    componentYPTrajectories(~validComponentNeurons, :, :, :, :) = 0;
    componentValueAxis = rawValueAxis;
    componentValueAxis(~validComponentNeurons) = 0;
    componentValueAxis = componentValueAxis / ...
        norm(componentValueAxis);
    componentYPProjection = reshape(componentValueAxis' * ...
        reshape(componentYPTrajectories, nNeurons, []), ...
        5, 9, 2, nTimes);

    validReducedResidualNeurons = all(reshape( ...
        isfinite(reducedResidualYPTrajectories), ...
        nNeurons, []), 2) & isfinite(rawValueAxis);
    reducedResidualYPTrajectories( ...
        ~validReducedResidualNeurons, :, :, :) = 0;
    reducedResidualValueAxis = rawValueAxis;
    reducedResidualValueAxis(~validReducedResidualNeurons) = 0;
    reducedResidualValueAxis = reducedResidualValueAxis / ...
        norm(reducedResidualValueAxis);
    reducedResidualYPProjection = reshape( ...
        reducedResidualValueAxis' * reshape( ...
        reducedResidualYPTrajectories, nNeurons, []), ...
        9, 2, nTimes);

    validChoiceOnlyResidualNeurons = all(reshape( ...
        isfinite(choiceOnlyResidualYPTrajectories), ...
        nNeurons, []), 2) & isfinite(rawValueAxis);
    choiceOnlyResidualYPTrajectories( ...
        ~validChoiceOnlyResidualNeurons, :, :, :) = 0;
    choiceOnlyResidualValueAxis = rawValueAxis;
    choiceOnlyResidualValueAxis( ...
        ~validChoiceOnlyResidualNeurons) = 0;
    choiceOnlyResidualValueAxis = choiceOnlyResidualValueAxis / ...
        norm(choiceOnlyResidualValueAxis);
    choiceOnlyResidualYPProjection = reshape( ...
        choiceOnlyResidualValueAxis' * reshape( ...
        choiceOnlyResidualYPTrajectories, nNeurons, []), ...
        9, 2, nTimes);

    validMotorOnlyResidualNeurons = all(reshape( ...
        isfinite(motorOnlyResidualYPTrajectories), ...
        nNeurons, []), 2) & isfinite(rawValueAxis);
    motorOnlyResidualYPTrajectories( ...
        ~validMotorOnlyResidualNeurons, :, :, :) = 0;
    motorOnlyResidualValueAxis = rawValueAxis;
    motorOnlyResidualValueAxis( ...
        ~validMotorOnlyResidualNeurons) = 0;
    motorOnlyResidualValueAxis = motorOnlyResidualValueAxis / ...
        norm(motorOnlyResidualValueAxis);
    motorOnlyResidualYPProjection = reshape( ...
        motorOnlyResidualValueAxis' * reshape( ...
        motorOnlyResidualYPTrajectories, nNeurons, []), ...
        9, 2, nTimes);

    populationUniqueSS = reshape(sum( ...
        uniqueExplainedSS, 1, 'omitnan'), 3, nTimes);
    uniqueSSTotal = sum(populationUniqueSS, 1);
    relativeUniqueExplainedVariance = ...
        100*populationUniqueSS./uniqueSSTotal;
    relativeUniqueExplainedVariance(:, ...
        ~isfinite(uniqueSSTotal) | uniqueSSTotal <= eps) = nan;
    populationTotalSS = sum(totalSS, 1, 'omitnan');
    populationFullExplainedSS = sum( ...
        fullModelExplainedSS, 1, 'omitnan');
    populationFullModelR2 = ...
        populationFullExplainedSS./populationTotalSS;
    populationFullModelR2( ...
        ~isfinite(populationTotalSS) | ...
        populationTotalSS <= eps) = nan;

    pilot3Regression.animals(animalIndex).name = ...
        animalNames(animalIndex);
    pilot3Regression.animals(animalIndex).time_at = timeAt;
    pilot3Regression.animals(animalIndex).parameter_projection = ...
        parameterProjection;
    pilot3Regression.animals(animalIndex).condition_baselines = ...
        conditionBaselines;
    pilot3Regression.animals(animalIndex).n_valid_neurons = ...
        sum(validNeurons);
    pilot3Regression.animals(animalIndex). ...
        corrected_YP_projection = correctedYPProjection;
    pilot3Regression.animals(animalIndex). ...
        n_valid_corrected_neurons = sum(validCorrectedNeurons);
    pilot3Regression.animals(animalIndex). ...
        component_YP_projection = componentYPProjection;
    pilot3Regression.animals(animalIndex). ...
        n_valid_component_neurons = sum(validComponentNeurons);
    pilot3Regression.animals(animalIndex). ...
        reduced_residual_YP_projection = ...
        reducedResidualYPProjection;
    pilot3Regression.animals(animalIndex). ...
        reduced_beta_time = reducedBetaTime;
    pilot3Regression.animals(animalIndex). ...
        n_valid_reduced_residual_neurons = ...
        sum(validReducedResidualNeurons);
    pilot3Regression.animals(animalIndex). ...
        choice_only_residual_YP_projection = ...
        choiceOnlyResidualYPProjection;
    pilot3Regression.animals(animalIndex). ...
        choice_only_beta_time = choiceOnlyBetaTime;
    pilot3Regression.animals(animalIndex). ...
        n_valid_choice_only_residual_neurons = ...
        sum(validChoiceOnlyResidualNeurons);
    pilot3Regression.animals(animalIndex). ...
        motor_only_residual_YP_projection = ...
        motorOnlyResidualYPProjection;
    pilot3Regression.animals(animalIndex). ...
        motor_only_beta_time = motorOnlyBetaTime;
    pilot3Regression.animals(animalIndex). ...
        n_valid_motor_only_residual_neurons = ...
        sum(validMotorOnlyResidualNeurons);
    pilot3Regression.animals(animalIndex). ...
        unique_explained_ss = uniqueExplainedSS;
    pilot3Regression.animals(animalIndex). ...
        population_unique_explained_ss = populationUniqueSS;
    pilot3Regression.animals(animalIndex). ...
        relative_unique_explained_variance = ...
        relativeUniqueExplainedVariance;
    pilot3Regression.animals(animalIndex). ...
        population_full_model_R2 = populationFullModelR2;

    for windowIndex = 1:size(analysisWindows, 1)
        window = analysisWindows(windowIndex, :);
        timeMask = timeAt >= window(1) & timeAt < window(2);
        windowParameters = mean( ...
            parameterProjection(:, timeMask), 2, 'omitnan');
        pilot3Rows(end + 1, :) = { ...
            animalNames(animalIndex), window(1), window(2), ...
            windowParameters(1), windowParameters(2), ...
            windowParameters(3), windowParameters(4), ...
            sum(validNeurons)}; %#ok<SAGROW>
    end
end

pilot3WindowStats = cell2table(pilot3Rows, ...
    'VariableNames', {'Animal', 'WindowStart', 'WindowEnd', ...
    'Intercept', 'Choice', 'Release1', ...
    'ChoiceByRelease1', 'NValidNeurons'});
disp(pilot3WindowStats);

%% Plot every projected regression parameter
figure('Color', 'w', ...
    'Name', 'Condition-baseline-corrected value-axis regression', ...
    'Position', [100 100 1100 700]);
tiledlayout(2, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
for parameterIndex = 1:numel(parameterNames)
    nexttile;
    hold on;
    for animalIndex = 1:numel(animalNames)
        result = pilot3Regression.animals(animalIndex);
        smoothingBins = max(1, round( ...
            50 / median(diff(result.time_at))));
        parameterTimeCourse = smoothdata( ...
            result.parameter_projection(parameterIndex, :), ...
            'gaussian', smoothingBins);
        plot(result.time_at, parameterTimeCourse, ...
            'Color', animalColors(animalIndex, :), ...
            'LineWidth', 1.8);
    end
    xline(0, '--', 'Color', [0.4 0.4 0.4]);
    yline(0, ':', 'Color', [0.65 0.65 0.65]);
    xlim([-250 1000]);
    set(gca, 'XTick', -250:250:1000, 'FontSize', 11);
    title(parameterNames(parameterIndex), 'Interpreter', 'none');
    xlabel('Time from GO onset (ms)');
    ylabel('Coefficient on value axis');
    box off;
    if parameterIndex == 1
        legend(cellstr(animalNames), 'Location', 'best', ...
            'Box', 'off');
    end
end
sgtitle({'Regression after condition-specific baseline subtraction', ...
    '\Delta firing(t) = \alpha + \beta_C C + \beta_M M + \beta_{CM}CM'});

%% Relative unique explained variance in the full model
predictorNames = {'Choice', 'Release1', ...
    'Choice x Release1'};
predictorColors = [ ...
    0.20 0.45 0.75; ...
    0.85 0.35 0.20; ...
    0.55 0.35 0.70];
figure('Color', 'w', ...
    'Name', 'Relative explained variance in full model', ...
    'Position', [100 100 1150 540]);
relativeVarianceLayout = tiledlayout(1, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');
for animalIndex = 1:numel(animalNames)
    nexttile;
    result = pilot3Regression.animals(animalIndex);
    timeAt = result.time_at;
    smoothingBins = max(1, round( ...
        50/median(diff(timeAt))));

    % Smooth the unique sums of squares before converting them to
    % percentages, so that the three stacked contributions remain 100%.
    uniqueSS = smoothdata( ...
        result.population_unique_explained_ss, ...
        2, 'gaussian', smoothingBins);
    uniqueSSTotal = sum(uniqueSS, 1);
    relativeExplainedVariance = 100*uniqueSS./uniqueSSTotal;
    relativeExplainedVariance(:, ...
        ~isfinite(uniqueSSTotal) | uniqueSSTotal <= eps) = nan;

    areaHandles = area(timeAt, ...
        uniqueSS', ...
        'LineStyle', 'none');
    for predictorIndex = 1:numel(predictorNames)
        areaHandles(predictorIndex).FaceColor = ...
            predictorColors(predictorIndex, :);
        areaHandles(predictorIndex).FaceAlpha = 0.85;
    end
    xline(0, '--k', 'LineWidth', 1);
    xlim([-250 1000]);
    % ylim([0 100]);
    set(gca, ...
        'XTick', -250:250:1000, ...
        'YTick', 0:20:100, ...
        'FontSize', 11);
    xlabel('Time from GO cue onset (ms)');
    ylabel('Relative unique explained variance (%)');
    title(animalNames(animalIndex));
    box off;
end
relativeVarianceLegend = legend( ...
    areaHandles, predictorNames, ...
    'Orientation', 'horizontal', ...
    'Box', 'off');
relativeVarianceLegend.Layout.Tile = 'south';
title(relativeVarianceLayout, { ...
    'Relative unique explained variance in the full model', ...
    ['Drop-one \DeltaSSE, normalized across choice, ' ...
    'release1, and their interaction']});

%% Reproduce Figure_YP A-B after removing choice and motor main effects
yellowColor = [0.90 0.65 0.05];
purpleColor = [0.55 0.25 0.72];
figure('Color', 'w', ...
    'Name', 'Y/P after removing choice and release1 effects', ...
    'Position', [100 100 1100 470]);
tiledlayout(1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
for animalIndex = 1:numel(animalNames)
    nexttile;
    hold on;
    result = pilot3Regression.animals(animalIndex);
    timeAt = result.time_at;
    correctedProjection = result.corrected_YP_projection;
    yellowValue = reshape(correctedProjection(:, 1, :), ...
        9, numel(timeAt));
    purpleValue = reshape(correctedProjection(:, 2, :), ...
        9, numel(timeAt));

    yellowMean = mean(yellowValue, 1, 'omitnan');
    yellowSE = std(yellowValue, 0, 1, 'omitnan') / ...
        sqrt(size(yellowValue, 1));
    purpleMean = mean(purpleValue, 1, 'omitnan');
    purpleSE = std(purpleValue, 0, 1, 'omitnan') / ...
        sqrt(size(purpleValue, 1));

    fill([timeAt, fliplr(timeAt)], ...
        [yellowMean - yellowSE, ...
        fliplr(yellowMean + yellowSE)], ...
        yellowColor, 'FaceAlpha', 0.20, ...
        'EdgeColor', 'none');
    fill([timeAt, fliplr(timeAt)], ...
        [purpleMean - purpleSE, ...
        fliplr(purpleMean + purpleSE)], ...
        purpleColor, 'FaceAlpha', 0.20, ...
        'EdgeColor', 'none');
    yellowLine = plot(timeAt, yellowMean, ...
        'Color', yellowColor, 'LineWidth', 1.8);
    purpleLine = plot(timeAt, purpleMean, ...
        'Color', purpleColor, 'LineWidth', 1.8);

    pValue = nan(1, numel(timeAt));
    for timeIndex = 1:numel(timeAt)
        [~, pValue(timeIndex)] = ttest( ...
            purpleValue(:, timeIndex) - ...
            yellowValue(:, timeIndex));
    end
    significantTime = pValue < 0.05 & ...
        timeAt >= -250 & timeAt <= 500;
    upperEnvelope = max([yellowMean + yellowSE; ...
        purpleMean + purpleSE], [], 1);
    projectionRange = max(upperEnvelope) - ...
        min([yellowMean - yellowSE, purpleMean - purpleSE]);
    significanceHeight = upperEnvelope + ...
        0.04 * max(projectionRange, eps);
    plot(timeAt(significantTime), ...
        significanceHeight(significantTime), ...
        'k.', 'MarkerSize', 5);

    xline(0, '--', 'Color', [0.4 0.4 0.4]);
    yline(0, ':', 'Color', [0.65 0.65 0.65]);
    xlim([-250 500]);
    set(gca, 'XTick', -250:250:500, 'FontSize', 11);
    xlabel('Time from GO cue onset (ms)');
    ylabel('Choice/motor-corrected value-axis projection');
    title(animalNames(animalIndex));
    box off;
    if animalIndex == 2
        legend([yellowLine, purpleLine], ...
            {'Yellow', 'Purple'}, 'Location', 'best', ...
            'Box', 'off');
    end
end
sgtitle({'Yellow/Purple after removing choice and release1 main effects', ...
    'Dots: paired condition-level p < 0.05'});

%% Five-component reconstruction of Yellow/Purple trajectories
figure('Color', 'w', ...
    'Name', 'Y/P regression-component trajectories', ...
    'Position', [100 50 1200 1000]);
tiledlayout(5, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
componentAxes = gobjects(5, 2);
for componentIndex = 1:numel(componentNames)
    for animalIndex = 1:numel(animalNames)
        componentAxes(componentIndex, animalIndex) = nexttile;
        hold on;
        result = pilot3Regression.animals(animalIndex);
        timeAt = result.time_at;
        componentProjection = reshape( ...
            result.component_YP_projection( ...
            componentIndex, :, :, :), ...
            9, 2, numel(timeAt));
        yellowValue = reshape(componentProjection(:, 1, :), ...
            9, numel(timeAt));
        purpleValue = reshape(componentProjection(:, 2, :), ...
            9, numel(timeAt));
        yellowMean = mean(yellowValue, 1, 'omitnan');
        purpleMean = mean(purpleValue, 1, 'omitnan');
        yellowSE = std(yellowValue, 0, 1, 'omitnan') / ...
            sqrt(size(yellowValue, 1));
        purpleSE = std(purpleValue, 0, 1, 'omitnan') / ...
            sqrt(size(purpleValue, 1));

        fill([timeAt, fliplr(timeAt)], ...
            [yellowMean - yellowSE, ...
            fliplr(yellowMean + yellowSE)], ...
            yellowColor, 'FaceAlpha', 0.20, ...
            'EdgeColor', 'none');
        fill([timeAt, fliplr(timeAt)], ...
            [purpleMean - purpleSE, ...
            fliplr(purpleMean + purpleSE)], ...
            purpleColor, 'FaceAlpha', 0.20, ...
            'EdgeColor', 'none');
        yellowLine = plot(timeAt, yellowMean, ...
            'Color', yellowColor, 'LineWidth', 1.6);
        purpleLine = plot(timeAt, purpleMean, ...
            'Color', purpleColor, 'LineWidth', 1.6);
        xline(0, '--', 'Color', [0.4 0.4 0.4]);
        yline(0, ':', 'Color', [0.65 0.65 0.65]);
        xlim([-250 1000]);
        set(gca, 'XTick', -250:250:1000, 'FontSize', 10);
        title(sprintf('%s: %s', ...
            animalNames(animalIndex), ...
            componentNames(componentIndex)), ...
            'Interpreter', 'none');
        ylabel('Value-axis projection');
        box off;
        if componentIndex == numel(componentNames)
            xlabel('Time from GO cue onset (ms)');
        end
        if componentIndex == 1 && animalIndex == 2
            legend([yellowLine, purpleLine], ...
                {'Yellow', 'Purple'}, 'Location', 'best', ...
                'Box', 'off');
        end
    end
    linkaxes(componentAxes(componentIndex, :), 'y');
end
sgtitle(['Yellow/Purple trajectories reconstructed from ' ...
    'individual regression components']);

%% Residual from reduced model without the choice-by-release1 interaction
figure('Color', 'w', ...
    'Name', 'Y/P residual without interaction in regression', ...
    'Position', [100 100 1100 470]);
tiledlayout(1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
for animalIndex = 1:numel(animalNames)
    nexttile;
    hold on;
    result = pilot3Regression.animals(animalIndex);
    timeAt = result.time_at;
    residualProjection = ...
        result.reduced_residual_YP_projection;
    yellowValue = reshape(residualProjection(:, 1, :), ...
        9, numel(timeAt));
    purpleValue = reshape(residualProjection(:, 2, :), ...
        9, numel(timeAt));
    yellowMean = mean(yellowValue, 1, 'omitnan');
    purpleMean = mean(purpleValue, 1, 'omitnan');
    yellowSE = std(yellowValue, 0, 1, 'omitnan') / ...
        sqrt(size(yellowValue, 1));
    purpleSE = std(purpleValue, 0, 1, 'omitnan') / ...
        sqrt(size(purpleValue, 1));

    fill([timeAt, fliplr(timeAt)], ...
        [yellowMean - yellowSE, ...
        fliplr(yellowMean + yellowSE)], ...
        yellowColor, 'FaceAlpha', 0.20, ...
        'EdgeColor', 'none');
    fill([timeAt, fliplr(timeAt)], ...
        [purpleMean - purpleSE, ...
        fliplr(purpleMean + purpleSE)], ...
        purpleColor, 'FaceAlpha', 0.20, ...
        'EdgeColor', 'none');
    yellowLine = plot(timeAt, yellowMean, ...
        'Color', yellowColor, 'LineWidth', 1.8);
    purpleLine = plot(timeAt, purpleMean, ...
        'Color', purpleColor, 'LineWidth', 1.8);

    pValue = nan(1, numel(timeAt));
    for timeIndex = 1:numel(timeAt)
        [~, pValue(timeIndex)] = ttest( ...
            purpleValue(:, timeIndex) - ...
            yellowValue(:, timeIndex));
    end
    significantTime = pValue < 0.05 & ...
        timeAt >= -250 & timeAt <= 1000;
    upperEnvelope = max([yellowMean + yellowSE; ...
        purpleMean + purpleSE], [], 1);
    projectionRange = max(upperEnvelope) - ...
        min([yellowMean - yellowSE, purpleMean - purpleSE]);
    significanceHeight = upperEnvelope + ...
        0.04 * max(projectionRange, eps);
    plot(timeAt(significantTime), ...
        significanceHeight(significantTime), ...
        'k.', 'MarkerSize', 5);

    xline(0, '--', 'Color', [0.4 0.4 0.4]);
    yline(0, ':', 'Color', [0.65 0.65 0.65]);
    xlim([-250 1000]);
    set(gca, 'XTick', -250:250:1000, 'FontSize', 11);
    xlabel('Time from GO cue onset (ms)');
    ylabel('Reduced-model residual on value axis');
    title(animalNames(animalIndex));
    box off;
    if animalIndex == 2
        legend([yellowLine, purpleLine], ...
            {'Yellow', 'Purple'}, 'Location', 'best', ...
            'Box', 'off');
    end
end
sgtitle({'Residual after fitting intercept + choice + release1', ...
    'Interaction omitted; dots indicate paired-condition p < 0.05'});

%% Residual from model containing only intercept and choice
figure('Color', 'w', ...
    'Name', 'Y/P residual from choice-only regression', ...
    'Position', [100 100 1100 470]);
tiledlayout(1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
for animalIndex = 1:numel(animalNames)
    nexttile;
    hold on;
    result = pilot3Regression.animals(animalIndex);
    timeAt = result.time_at;
    residualProjection = ...
        result.choice_only_residual_YP_projection;
    yellowValue = reshape(residualProjection(:, 1, :), ...
        9, numel(timeAt));
    purpleValue = reshape(residualProjection(:, 2, :), ...
        9, numel(timeAt));
    yellowMean = mean(yellowValue, 1, 'omitnan');
    purpleMean = mean(purpleValue, 1, 'omitnan');
    yellowSE = std(yellowValue, 0, 1, 'omitnan') / ...
        sqrt(size(yellowValue, 1));
    purpleSE = std(purpleValue, 0, 1, 'omitnan') / ...
        sqrt(size(purpleValue, 1));

    fill([timeAt, fliplr(timeAt)], ...
        [yellowMean - yellowSE, ...
        fliplr(yellowMean + yellowSE)], ...
        yellowColor, 'FaceAlpha', 0.20, ...
        'EdgeColor', 'none');
    fill([timeAt, fliplr(timeAt)], ...
        [purpleMean - purpleSE, ...
        fliplr(purpleMean + purpleSE)], ...
        purpleColor, 'FaceAlpha', 0.20, ...
        'EdgeColor', 'none');
    yellowLine = plot(timeAt, yellowMean, ...
        'Color', yellowColor, 'LineWidth', 1.8);
    purpleLine = plot(timeAt, purpleMean, ...
        'Color', purpleColor, 'LineWidth', 1.8);

    pValue = nan(1, numel(timeAt));
    for timeIndex = 1:numel(timeAt)
        [~, pValue(timeIndex)] = ttest( ...
            purpleValue(:, timeIndex) - ...
            yellowValue(:, timeIndex));
    end
    significantTime = pValue < 0.05 & ...
        timeAt >= -250 & timeAt <= 1000;
    upperEnvelope = max([yellowMean + yellowSE; ...
        purpleMean + purpleSE], [], 1);
    projectionRange = max(upperEnvelope) - ...
        min([yellowMean - yellowSE, purpleMean - purpleSE]);
    significanceHeight = upperEnvelope + ...
        0.04 * max(projectionRange, eps);
    plot(timeAt(significantTime), ...
        significanceHeight(significantTime), ...
        'k.', 'MarkerSize', 5);

    xline(0, '--', 'Color', [0.4 0.4 0.4]);
    yline(0, ':', 'Color', [0.65 0.65 0.65]);
    xlim([-250 1000]);
    set(gca, 'XTick', -250:250:1000, 'FontSize', 11);
    xlabel('Time from GO cue onset (ms)');
    ylabel('Choice-only model residual on value axis');
    title(animalNames(animalIndex));
    box off;
    if animalIndex == 2
        legend([yellowLine, purpleLine], ...
            {'Yellow', 'Purple'}, 'Location', 'best', ...
            'Box', 'off');
    end
end
sgtitle({'Residual after fitting intercept + choice only', ...
    'Dots indicate paired-condition p < 0.05'});

%% Residual from model containing only intercept and release1
figure('Color', 'w', ...
    'Name', 'Y/P residual from motor-only regression', ...
    'Position', [100 100 1100 470]);
tiledlayout(1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
for animalIndex = 1:numel(animalNames)
    nexttile;
    hold on;
    result = pilot3Regression.animals(animalIndex);
    timeAt = result.time_at;
    residualProjection = ...
        result.motor_only_residual_YP_projection;
    yellowValue = reshape(residualProjection(:, 1, :), ...
        9, numel(timeAt));
    purpleValue = reshape(residualProjection(:, 2, :), ...
        9, numel(timeAt));
    yellowMean = mean(yellowValue, 1, 'omitnan');
    purpleMean = mean(purpleValue, 1, 'omitnan');
    yellowSE = std(yellowValue, 0, 1, 'omitnan') / ...
        sqrt(size(yellowValue, 1));
    purpleSE = std(purpleValue, 0, 1, 'omitnan') / ...
        sqrt(size(purpleValue, 1));

    fill([timeAt, fliplr(timeAt)], ...
        [yellowMean - yellowSE, ...
        fliplr(yellowMean + yellowSE)], ...
        yellowColor, 'FaceAlpha', 0.20, ...
        'EdgeColor', 'none');
    fill([timeAt, fliplr(timeAt)], ...
        [purpleMean - purpleSE, ...
        fliplr(purpleMean + purpleSE)], ...
        purpleColor, 'FaceAlpha', 0.20, ...
        'EdgeColor', 'none');
    yellowLine = plot(timeAt, yellowMean, ...
        'Color', yellowColor, 'LineWidth', 1.8);
    purpleLine = plot(timeAt, purpleMean, ...
        'Color', purpleColor, 'LineWidth', 1.8);

    pValue = nan(1, numel(timeAt));
    for timeIndex = 1:numel(timeAt)
        [~, pValue(timeIndex)] = ttest( ...
            purpleValue(:, timeIndex) - ...
            yellowValue(:, timeIndex));
    end
    significantTime = pValue < 0.05 & ...
        timeAt >= -250 & timeAt <= 1000;
    upperEnvelope = max([yellowMean + yellowSE; ...
        purpleMean + purpleSE], [], 1);
    projectionRange = max(upperEnvelope) - ...
        min([yellowMean - yellowSE, purpleMean - purpleSE]);
    significanceHeight = upperEnvelope + ...
        0.04 * max(projectionRange, eps);
    plot(timeAt(significantTime), ...
        significanceHeight(significantTime), ...
        'k.', 'MarkerSize', 5);

    xline(0, '--', 'Color', [0.4 0.4 0.4]);
    yline(0, ':', 'Color', [0.65 0.65 0.65]);
    xlim([-250 1000]);
    set(gca, 'XTick', -250:250:1000, 'FontSize', 11);
    xlabel('Time from GO cue onset (ms)');
    ylabel('Motor-only model residual on value axis');
    title(animalNames(animalIndex));
    box off;
    if animalIndex == 2
        legend([yellowLine, purpleLine], ...
            {'Yellow', 'Purple'}, 'Location', 'best', ...
            'Box', 'off');
    end
end
sgtitle({'Residual after fitting intercept + release1 only', ...
    'Dots indicate paired-condition p < 0.05'});
