%% Compare window-specific PC1 with the GO-locked value-coding axes
% PCA is computed separately in five 250-ms windows around the GO signal.
% Because neurons were recorded across sessions, individual trials are
% combined into a condition-stratified pseudopopulation. Trial identities
% are independently permuted for each neuron within condition.

if ~exist('go', 'var')
    data = W.load('../../TempData/data');
    go = data.go;
end
valueAxis = W.load('../../TempData/value_axisGO');

windowEdges = [-250 0; 0 250; 250 500; 500 750; 750 1000];
windowLabels = arrayfun(@(windowIndex)sprintf( ...
    '%d:%d ms', windowEdges(windowIndex, 1), ...
    windowEdges(windowIndex, 2)), ...
    (1:size(windowEdges, 1))', 'UniformOutput', false);
animalNames = ["Monkey S", "Monkey T"];
nConditions = 9;
nWindows = size(windowEdges, 1);
nDeltaWindows = nWindows - 1;
deltaWindowLabels = arrayfun(@(windowIndex)sprintf( ...
    '[%d,%d] - [%d,%d] ms', ...
    windowEdges(windowIndex + 1, 1), ...
    windowEdges(windowIndex + 1, 2), ...
    windowEdges(windowIndex, 1), ...
    windowEdges(windowIndex, 2)), ...
    (1:nDeltaWindows)', 'UniformOutput', false);

pilot5 = struct;
pilot5.settings = W.struct( ...
    'lock', 'go signal', ...
    'window_edges_ms', windowEdges, ...
    'pca_observations', ...
    ['adjacent-window differences in a condition-stratified ' ...
    'individual-trial pseudopopulation'], ...
    'pseudopopulation_seed', 1, ...
    'pseudopopulation_sampling', ...
    ['without replacement; equal trial count per condition; ' ...
    'same trial pairing reused across time windows'], ...
    'neuron_normalization', ...
    'z-score pseudotrial responses within each neuron and window', ...
    'similarity', ...
    ['absolute cosine; PC1 sign is aligned to the corresponding ' ...
    'value axis'], ...
    'value_axis_file', '../../TempData/value_axisGO');
pilot5.animals = repmat(struct, numel(animalNames), 1);
trajectoryChangeRows = cell(0, 8);
previousRandomState = rng;
rng(1, 'twister');

for animalIndex = 1:numel(animalNames)
    d = go{animalIndex};
    nNeurons = numel(d.cells);
    assert(nNeurons == size( ...
        valueAxis.animals(animalIndex).axis_unit, 1), ...
        'The PCA data and value axes contain different neuron counts.');
    assert(isequal(d.info_cells, ...
        valueAxis.animals(animalIndex).info_cells), ...
        'The PCA data and value axes have different neuron ordering.');

    pc1Unit = nan(nNeurons, nDeltaWindows);
    conditionActivity = nan(nConditions, nNeurons, nWindows);

    % Select independently paired trials for every neuron. Using the
    % minimum count across all neuron-condition combinations makes every
    % condition contribute equally to PCA.
    trialCounts = nan(nConditions, nNeurons);
    conditionTrialIndices = cell(nConditions, nNeurons);
    for neuronIndex = 1:nNeurons
        game = d.games{d.info_cells.gameID(neuronIndex)};
        spikes = d.cells{neuronIndex};
        validAcrossWindows = true(height(game), 1);
        for windowIndex = 1:nWindows
            validityTimeMask = ...
                d.time_at >= windowEdges(windowIndex, 1) & ...
                d.time_at < windowEdges(windowIndex, 2);
            windowResponse = mean( ...
                spikes(:, validityTimeMask), 2, 'omitnan');
            validAcrossWindows = validAcrossWindows & ...
                isfinite(windowResponse);
        end
        for condition = 1:nConditions
            conditionTrialIndices{condition, neuronIndex} = ...
                find(game.condition == condition & validAcrossWindows);
            trialCounts(condition, neuronIndex) = numel( ...
                conditionTrialIndices{condition, neuronIndex});
        end
    end
    nPseudoTrialsPerCondition = min(trialCounts, [], 'all');
    assert(nPseudoTrialsPerCondition >= 2, ...
        'Each neuron-condition pair needs at least two trials.');
    pseudoTrialIndices = cell(nConditions, nNeurons);
    for neuronIndex = 1:nNeurons
        for condition = 1:nConditions
            availableTrials = conditionTrialIndices{ ...
                condition, neuronIndex};
            permutation = randperm(numel(availableTrials), ...
                nPseudoTrialsPerCondition);
            pseudoTrialIndices{condition, neuronIndex} = ...
                availableTrials(permutation);
        end
    end
    nPseudoTrials = nConditions * nPseudoTrialsPerCondition;
    pseudoCondition = repelem( ...
        (1:nConditions)', nPseudoTrialsPerCondition);
    pseudoTrialActivity = nan(nPseudoTrials, nNeurons, nWindows);

    for windowIndex = 1:nWindows
        timeMask = d.time_at >= windowEdges(windowIndex, 1) & ...
            d.time_at < windowEdges(windowIndex, 2);
        assert(any(timeMask), ...
            'A requested PCA window contains no time samples.');

        for neuronIndex = 1:nNeurons
            spikes = d.cells{neuronIndex};
            game = d.games{d.info_cells.gameID(neuronIndex)};
            assert(size(spikes, 1) == height(game), ...
                'Spike trials and behavioral trials must match.');

            trialResponse = mean( ...
                spikes(:, timeMask), 2, 'omitnan');
            conditionMean = W.cond_average( ...
                trialResponse, game.condition, 1:nConditions);
            conditionActivity(:, neuronIndex, windowIndex) = ...
                conditionMean(:);

            for condition = 1:nConditions
                rowStart = ...
                    (condition - 1) * nPseudoTrialsPerCondition + 1;
                rowEnd = condition * nPseudoTrialsPerCondition;
                selectedTrials = pseudoTrialIndices{ ...
                    condition, neuronIndex};
                pseudoTrialActivity(rowStart:rowEnd, ...
                    neuronIndex, windowIndex) = ...
                    trialResponse(selectedTrials);
            end
        end

    end

    % PCA is performed on trial-wise activity changes between adjacent
    % windows, not on activity from either window alone.
    for deltaWindowIndex = 1:nDeltaWindows
        currentActivity = ...
            pseudoTrialActivity(:, :, deltaWindowIndex + 1) - ...
            pseudoTrialActivity(:, :, deltaWindowIndex);
        neuronMean = mean(currentActivity, 1, 'omitnan');
        neuronScale = std(currentActivity, 0, 1, 'omitnan');
        neuronScale(~isfinite(neuronScale) | neuronScale <= eps) = 1;
        normalizedActivity = ...
            (currentActivity - neuronMean)./neuronScale;
        assert(all(isfinite(normalizedActivity), 'all'), ...
            'Pseudotrial activity must be finite for PCA.');

        % Rows are individual pseudotrials and columns are neurons. The
        % first right singular vector is the trial-level PC1 neuron axis.
        [~, ~, neuronLoadings] = svd( ...
            normalizedActivity, 'econ');
        pc1 = neuronLoadings(:, 1);

        % Orient the delta PC1 toward the value axis defined in the
        % starting window of that change.
        correspondingValueAxis = valueAxis.animals( ...
            animalIndex).axis_unit(:, deltaWindowIndex);
        if dot(pc1, correspondingValueAxis) < 0
            pc1 = -pc1;
        end
        pc1Unit(:, deltaWindowIndex) = pc1/norm(pc1);
    end

    valueAxisUnit = valueAxis.animals(animalIndex).axis_unit;
    cosineSigned = pc1Unit' * valueAxisUnit;
    cosineAbsolute = abs(cosineSigned);
    matchedStartWindowCosine = arrayfun( ...
        @(deltaWindowIndex)cosineAbsolute( ...
        deltaWindowIndex, deltaWindowIndex), ...
        (1:nDeltaWindows)');
    matchedEndWindowCosine = arrayfun( ...
        @(deltaWindowIndex)cosineAbsolute( ...
        deltaWindowIndex, deltaWindowIndex + 1), ...
        (1:nDeltaWindows)');
    preGoValueAxisCosine = cosineAbsolute(:, 1);

    pilot5.animals(animalIndex).name = animalNames(animalIndex);
    pilot5.animals(animalIndex).info_cells = d.info_cells;
    pilot5.animals(animalIndex).condition_activity = ...
        conditionActivity;
    pilot5.animals(animalIndex).pseudo_trial_activity = ...
        pseudoTrialActivity;
    pilot5.animals(animalIndex).pseudo_condition = pseudoCondition;
    pilot5.animals(animalIndex).pseudo_trials_per_condition = ...
        nPseudoTrialsPerCondition;
    pilot5.animals(animalIndex).pc1_unit = pc1Unit;
    pilot5.animals(animalIndex).value_axis_unit = valueAxisUnit;
    pilot5.animals(animalIndex).cosine_signed = cosineSigned;
    pilot5.animals(animalIndex).cosine_absolute = cosineAbsolute;
    pilot5.animals(animalIndex).delta_window_labels = ...
        deltaWindowLabels;
    pilot5.animals(animalIndex).matched_start_window_cosine = ...
        matchedStartWindowCosine;
    pilot5.animals(animalIndex).matched_end_window_cosine = ...
        matchedEndWindowCosine;
    pilot5.animals(animalIndex).pre_go_value_axis_cosine = ...
        preGoValueAxisCosine;

    % Decompose the change from the pre-GO window to the first post-GO
    % window using the value axis defined in the pre-GO window. For each
    % condition, Delta x is a vector across neurons. Because the value axis
    % is unit length, squared norms of the parallel and orthogonal
    % components sum exactly to the total squared trajectory displacement.
    preWindowIndex = 1;
    postWindowIndex = 2;
    trajectoryChange = ...
        conditionActivity(:, :, postWindowIndex) - ...
        conditionActivity(:, :, preWindowIndex);
    preGoValueAxis = valueAxisUnit(:, preWindowIndex);
    preGoValueAxis = preGoValueAxis / norm(preGoValueAxis);
    valueScores = trajectoryChange * preGoValueAxis;
    valueParallelChange = valueScores * preGoValueAxis';
    orthogonalChange = trajectoryChange - valueParallelChange;

    totalEnergyByCondition = sum(trajectoryChange.^2, 2);
    valueEnergyByCondition = sum(valueParallelChange.^2, 2);
    orthogonalEnergyByCondition = sum(orthogonalChange.^2, 2);
    decompositionError = max(abs(totalEnergyByCondition - ...
        valueEnergyByCondition - orthogonalEnergyByCondition));
    assert(decompositionError < ...
        1e-10 * max(max(totalEnergyByCondition), 1), ...
        'Parallel and orthogonal trajectory energy must sum to total.');

    valuePercentByCondition = ...
        100 * valueEnergyByCondition ./ totalEnergyByCondition;
    orthogonalPercentByCondition = ...
        100 * orthogonalEnergyByCondition ./ totalEnergyByCondition;
    pooledTotalEnergy = sum(totalEnergyByCondition);
    pooledValuePercent = ...
        100 * sum(valueEnergyByCondition) / pooledTotalEnergy;
    pooledOrthogonalPercent = ...
        100 * sum(orthogonalEnergyByCondition) / pooledTotalEnergy;

    pilot5.animals(animalIndex).trajectory_change = trajectoryChange;
    pilot5.animals(animalIndex).trajectory_change_value_scores = ...
        valueScores;
    pilot5.animals(animalIndex).trajectory_change_value_parallel = ...
        valueParallelChange;
    pilot5.animals(animalIndex).trajectory_change_orthogonal = ...
        orthogonalChange;
    pilot5.animals(animalIndex).trajectory_change_total_energy = ...
        totalEnergyByCondition;
    pilot5.animals(animalIndex).trajectory_change_value_percent = ...
        valuePercentByCondition;
    pilot5.animals(animalIndex).trajectory_change_orthogonal_percent = ...
        orthogonalPercentByCondition;
    pilot5.animals(animalIndex).trajectory_change_pooled_value_percent = ...
        pooledValuePercent;
    pilot5.animals(animalIndex). ...
        trajectory_change_pooled_orthogonal_percent = ...
        pooledOrthogonalPercent;

    trajectoryChangeRows(end + 1, :) = { ...
        animalNames(animalIndex), pooledValuePercent, ...
        pooledOrthogonalPercent, mean(valuePercentByCondition), ...
        median(valuePercentByCondition), ...
        min(valuePercentByCondition), max(valuePercentByCondition), ...
        pooledTotalEnergy}; %#ok<SAGROW>

    fprintf('\n%s: delta-PC1 |cosine| with value axes\n', ...
        animalNames(animalIndex));
    for deltaWindowIndex = 1:nDeltaWindows
        fprintf(['  %s: start-axis %.3f, end-axis %.3f, ' ...
            'pre-GO axis %.3f\n'], ...
            deltaWindowLabels{deltaWindowIndex}, ...
            matchedStartWindowCosine(deltaWindowIndex), ...
            matchedEndWindowCosine(deltaWindowIndex), ...
            preGoValueAxisCosine(deltaWindowIndex));
    end
    fprintf(['  [0,250] minus [-250,0] trajectory energy: ' ...
        'value axis %.2f%%, orthogonal %.2f%%\n'], ...
        pooledValuePercent, pooledOrthogonalPercent);
end

rng(previousRandomState);
clear previousRandomState;

trajectoryChangeSummary = cell2table( ...
    trajectoryChangeRows, 'VariableNames', { ...
    'Animal', 'PooledValueAxisPercent', ...
    'PooledOrthogonalPercent', 'MeanConditionValueAxisPercent', ...
    'MedianConditionValueAxisPercent', ...
    'MinConditionValueAxisPercent', ...
    'MaxConditionValueAxisPercent', 'PooledTotalEnergy'});
pilot5.trajectory_change_summary = trajectoryChangeSummary;
disp(trajectoryChangeSummary);

W.save('../../TempData/pilot5_pc1_value_axis', ...
    'pilot5', pilot5);

%% Figure: PC1-to-value-axis similarity across training windows
figureHandle = figure( ...
    'Color', 'w', ...
    'Units', 'pixels', ...
    'Position', [100 100 1050 470]);
layout = tiledlayout(1, 2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

for animalIndex = 1:numel(animalNames)
    axesHandle = nexttile;
    similarity = ...
        pilot5.animals(animalIndex).cosine_absolute;
    imagesc(axesHandle, similarity, [0 1]);
    axis(axesHandle, 'tight');
    xticks(axesHandle, 1:nWindows);
    yticks(axesHandle, 1:nDeltaWindows);
    xticklabels(axesHandle, windowLabels);
    yticklabels(axesHandle, deltaWindowLabels);
    xtickangle(axesHandle, 35);
    xlabel(axesHandle, 'Value-axis window');
    ylabel(axesHandle, 'Delta-activity PC1 window');
    title(axesHandle, animalNames(animalIndex));
    colormap(axesHandle, parula);

    hold(axesHandle, 'on');
    for rowIndex = 1:nDeltaWindows
        for columnIndex = 1:nWindows
            if similarity(rowIndex, columnIndex) > 0.55
                textColor = 'w';
            else
                textColor = 'k';
            end
            text(axesHandle, columnIndex, rowIndex, ...
                sprintf('%.2f', similarity( ...
                rowIndex, columnIndex)), ...
                'Color', textColor, ...
                'HorizontalAlignment', 'center', ...
                'FontSize', 9);
        end
        rectangle(axesHandle, ...
            'Position', [rowIndex - 0.5, rowIndex - 0.5, 1, 1], ...
            'EdgeColor', 'w', ...
            'LineWidth', 1.5);
    end
end

colorBar = colorbar;
colorBar.Layout.Tile = 'east';
colorBar.Label.String = ...
    '|cosine similarity (PC1, value axis)|';
title(layout, ...
    ['GO-locked adjacent-window delta-PC1 alignment ' ...
    'with the value-coding axis']);

figureFolder = fullfile('..', '..', 'Figures');
if ~isfolder(figureFolder)
    mkdir(figureFolder);
end
figureBaseName = fullfile( ...
    figureFolder, 'PC1 versus value axis GO');
exportgraphics(figureHandle, figureBaseName + ".jpg", ...
    'Resolution', 180);
print(figureHandle, figureBaseName + ".svg", '-dsvg');
savefig(figureHandle, figureBaseName + ".fig");

% %% Figure: value-axis versus orthogonal trajectory-change energy
% decompositionFigure = figure( ...
%     'Color', 'w', ...
%     'Units', 'pixels', ...
%     'Position', [150 150 680 470]);
% decompositionValues = [ ...
%     trajectoryChangeSummary.PooledValueAxisPercent, ...
%     trajectoryChangeSummary.PooledOrthogonalPercent];
% barHandles = bar(decompositionValues, 'stacked');
% barHandles(1).FaceColor = [0.18 0.48 0.78];
% barHandles(2).FaceColor = [0.72 0.72 0.72];
% ylim([0 100]);
% yticks(0:20:100);
% xticks(1:numel(animalNames));
% xticklabels(cellstr(animalNames));
% ylabel('Trajectory-change energy (%)');
% legend({'Pre-GO value axis', 'Orthogonal activity'}, ...
%     'Location', 'southoutside', ...
%     'Orientation', 'horizontal', ...
%     'Box', 'off');
% title({ ...
%     'Population trajectory change: [0,250] minus [-250,0] ms', ...
%     'Squared displacement pooled across nine conditions'});
% box off;
% 
% for animalIndex = 1:numel(animalNames)
%     valuePercent = decompositionValues(animalIndex, 1);
%     orthogonalPercent = decompositionValues(animalIndex, 2);
%     text(animalIndex, valuePercent + 1.8, ...
%         sprintf('%.1f%%', valuePercent), ...
%         'HorizontalAlignment', 'center', ...
%         'Color', [0.05 0.20 0.40], 'FontWeight', 'bold');
%     text(animalIndex, valuePercent + orthogonalPercent / 2, ...
%         sprintf('%.1f%%', orthogonalPercent), ...
%         'HorizontalAlignment', 'center', ...
%         'Color', 'k', 'FontWeight', 'bold');
% end
% 
% decompositionBaseName = fullfile( ...
%     figureFolder, 'Trajectory change decomposition GO');
% exportgraphics(decompositionFigure, ...
%     decompositionBaseName + ".jpg", 'Resolution', 180);
% print(decompositionFigure, decompositionBaseName + ".svg", '-dsvg');
% savefig(decompositionFigure, decompositionBaseName + ".fig");
