%% Figure - baseline
drop = plt.custom_vars.drop;
delay = plt.custom_vars.delay;
tlt = plt.custom_vars.name_monkeys;
anv = W.load('../../TempData/anv_drop_delay_interaction_choice');
SW_fig(plt, anv{1}, anv{2}, ...
    'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
    'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 2, 1, 2,  ...
     'varargin_axes', {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', tlt(1)}, ...
     {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', tlt(2)}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', -0.05:0.01:0.05}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', -0.05:0.01:0.05}, ...
     'ABC_axes', 'CDEF', 'nx', 2, 'ny', 2, ...
     'varargin_fig', 'is_title', 'all', 'savename', 'ANOVA_drop_delay_interaction_choice');

for axi = 1:4
    plt.ax(axi);
    plt.matlabax(@(~)add_offer_onset_label(axi));
end
plt.update('ANOVA_drop_delay_interaction_choice');

function add_offer_onset_label(axi)
%ADD_OFFER_ONSET_LABEL Mark time zero below the current x-axis.
    ax = gca;
    x_limits = xlim(ax);
    y_limits = ylim(ax);
    label_y = y_limits(1) - 0.02*diff(y_limits);
    triangle_half_width = 0.012*diff(x_limits);
    triangle_height = 0.025*diff(y_limits);
    patch(ax, [-triangle_half_width triangle_half_width 0], ...
        [y_limits(1) - triangle_height, ...
        y_limits(1) - triangle_height, y_limits(1)], ...
        'black', 'EdgeColor', 'black', ...
        'Clipping', 'off');

    x_ticks = xticks(ax);
    x_tick_labels = string(xticklabels(ax));
    zero_tick = abs(x_ticks) < eps(max(abs(x_limits)));
    if numel(x_tick_labels) == numel(x_ticks)
        x_tick_labels(zero_tick) = "";
        xticklabels(ax, x_tick_labels);
    end

    text(ax, 0, label_y, sprintf('Offer\nOnset'), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontSize', max(ax.FontSize - 2, 8), ...
        'Clipping', 'off');

    if axi <= 2
        x_label = ax.XLabel;
        x_label_position = x_label.Position;
        x_label_position(2) = x_label_position(2) - 0.005;
        x_label.Position = x_label_position;
    else
        x_label = ax.XLabel;
        x_label_position = x_label.Position;
        x_label_position(2) = x_label_position(2) - 0.0005;
        x_label.Position = x_label_position;
    end
    % x_label.HorizontalAlignment = 'right';
end
