looper = S_looper_folder('../../Data/');
jobs = S_jobs();
jobs.set_loopers({'folder'}, {looper});
jobs.add_jobs_with_looper_folder([], 'event2trials', ...
    {'events'}, {'inputname1'}, 'trials');
jobs.add_jobs_with_looper_folder([], 'preprocess_trials', ...
    {'trials'}, {}, 'games');
%% cue period
% epoch cue -600 to 1100
jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_by_marker', ...
    {'spikes', 'trials'}, {1199, 1, -600:10:1100, 100}, 'epoch_cueon_600_1000');
jobs.add_jobs_with_looper_folder([], 'W.select_trials_cellgame', ...
    {'epoch_cueon_600_1000','games'},  {}, ...
    {'EPOCH_cue','games_cue'}, 'inputfunc', @(ev, g){ev, g, g.is_complete & ~g.is_post_error});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'EPOCH_cue', 'games_cue'}, {}, 'cue_all');
% epoch cue spike trains
jobs.add_jobs_with_looper_folder([], 'W.epoch_spiketrains_by_marker', ...
    {'spikes', 'trials'}, {1199, 1, -600, 1100, 1}, 'epoch_st_cueon_600_1000');
jobs.add_jobs_with_looper_folder([], 'W.select_trials_cellgame', ...
    {'epoch_st_cueon_600_1000','games'},  {}, ...
    {'ST_cue'}, 'inputfunc', @(ev, g){ev, g, g.is_complete & ~g.is_post_error});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'ST_cue', 'games_cue'}, {}, 'ST_cue_all');
%% go period
jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_by_marker', ...
    {'spikes', 'trials'}, {[1038 1121], 1, -600:10:1100, 100}, 'epoch_go_600_1100');
jobs.add_jobs_with_looper_folder([], 'W.select_trials_cellgame', ...
    {'epoch_go_600_1100','games'},  {}, ...
    {'EPOCH_go','games_go'}, 'inputfunc', @(ev, g){ev, g, g.is_complete & ~g.is_post_error});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'EPOCH_go', 'games_go'}, {}, 'go_all');
jobs.add_jobs_with_looper_folder([], 'W.epoch_spiketrains_by_marker', ...
    {'spikes', 'trials'}, {[1038 1121], 1, -600, 1100, 1}, 'epoch_st_go_600_1000');
jobs.add_jobs_with_looper_folder([], 'W.select_trials_cellgame', ...
    {'epoch_st_go_600_1000','games'},  {}, ...
    {'ST_go'}, 'inputfunc', @(ev, g){ev, g, g.is_complete & ~g.is_post_error});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'ST_go', 'games_go'}, {}, 'ST_go_all');
%%
jobs.parfor_off;
jobs.overwrite_off;
jobs.run()
%% merge ST and EPOCH
data = looper.looper_loadmix({'ST_cue_all','ST_go_all','cue_all', 'go_all'}, 'struct');
assert(isequal(data.cue_all.info_cells, data.ST_cue_all.info_cells));
assert(isequal(data.go_all.info_cells, data.ST_go_all.info_cells));
cue = data.ST_cue_all;
cue.ST = cue.cells;
cue.cells = data.cue_all.cells;
cue = W.struct_merge(cue, data.cue_all, 'ignore');
looper.looper_save_master(cue, 'cue');
go = data.ST_go_all;
go.ST = go.cells;
go.cells = data.go_all.cells;
go = W.struct_merge(go, data.go_all, 'ignore');
looper.looper_save_master(go, 'go');

















%% old codes - epoch cue 75 to 750
% jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_by_marker', ...
%     {'spikes', 'trials'}, {1199, 1, 412.5, 675, 'filter_appearance', 1}, 'epoch_cueon_75_750');
% jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
%     {'epoch_cueon_75_750','games'},  {}, ...
%     {'EPOCH_complete_75_750'});
% jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
%     {'EPOCH_complete_75_750', 'GAMES_complete'}, {}, 'epoch_75_750');
% %% shuffle
% jobs.add_jobs_with_looper_folder([], 'function_shuffle', ...
%     {'EPOCH_ST_complete'},  {}, ...
%     {'EPOCH_ST_complete_shuffled'}); 
% % jobs.power_on;
% jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_from_spiketrains', ...
%     {'EPOCH_ST_complete_shuffled'},  {-600:10:1100, 100}, ...
%     {'EPOCH_complete_shuffled'}); 
% %% shuffle
% % jobs.add_jobs_with_looper_folder([], 'function_shuffle_rate', ...
% %     {'EPOCH_ST_complete','GAMES_complete'},  {}, ...
% %     {'EPOCH_ST_complete_shuffled_rate'}); 
% % jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_from_spiketrains', ...
% %     {'EPOCH_ST_complete_shuffled_rate'},  {-600:10:1100, 100}, ...
% %     {'EPOCH_complete_shuffled_rate'}); 
% % jobs.power_on;
% jobs.add_jobs_with_looper_folder([], 'function_shuffle_rate', ...
%     {'EPOCH_complete'},  {}, ...
%     {'EPOCH_complete_shuffled_rate'}); 
% 
% % jobs.power_off;
% jobs.add_jobs_with_looper_folder([], 'function_filter0', ...
%     {'EPOCH_complete'}, {}, ...
%     {'EPOCH_complete_non0'});
% 
% jobs.add_jobs_with_looper_folder([], 'function_shuffle_trial', ...
%     {'EPOCH_ST_complete'},  {}, ...
%     {'EPOCH_ST_complete_shuffled_trial'}); 
% jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_from_spiketrains', ...
%     {'EPOCH_ST_complete_shuffled_trial'},  {-600:10:1100, 100}, ...
%     {'EPOCH_complete_shuffled_trial'}); 
%%
% looper.looper_copy('*all*', [], [], fullfile('../../TempData', looper.folders_names));
%% 